### PR TITLE
[IMP] agreement_legal: Improve multicompany management

### PR DESCRIPTION
**Pull request by etobella**
While checking the module I found there was a problem as you cannot define an agreement for another company. This should solve the problem.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I don't get the goal of the patch and the double field declaration. Why is it needed?

**Comment by etobella** [comment]
Without the patch the company is not editable. I wanted to show it when it was not multicompany but not editable and editable when we are in a multicompany environment

**Comment by pedrobaeza** [comment]
It's weird that adding `no_create: True` makes the field editable, but anyways, if it's the way, don't repeat the field and add it to the existing one with the multi-company group. Odoo doesn't show the company on the rest of models if you don't have such model. The reasoning behind it is that if you don't use the group, it's supposed you don't handle multiple companies, and thus, the company info is redundant.

**Comment by etobella** [comment]
Well, the change came from the readonly, the 'no_create' was no necessary. Now should be a lesser diff

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Do you let the group showing no matter the multi company group?

**Comment by etobella** [comment]
Yes, because without it the align of the information looses sense, there are other options, but it implies to change more the view

**Comment by pedrobaeza** [comment]
Ok, let's not complicate it more. Do you know why Travis is red?

**Review by olgamarcocb — APPROVED** [review]
:+1:

**Comment by etobella** [comment]
I don't know why it was red. I have rebased and now it seems right :smile:

**Pull request merged**
