### PR TITLE
[12.0][IMP] - contract termination

### LINKED ISSUE #458: [Enhancement] - Contract Resiliation
Hi, 

In some cases, customer ask to resiliate his contract and all services sold within.

With the current version, it's possible to achieve this by stopping all contract line at the resiliation date.

what is missing is: 
*  the possibility to highlight that was a contract resiliation
*  prevent users from resuming the contract.

I propose to:
*  Add a new user group that give the ability to resilite a contract 
*  Add a new button to the contract **Resiliate Contract**  that open a wizard and ask the user to set:
   *  Resiliation date
   *  Resiliation reason
*  The resiliation action will call the stop action at the resiliation date for each contract line
*  Add a Boolean field to identify a resiliated contract
*  A resiliated contract can't be edited
*  Add the mention **Resiliated** to the contract report
*  The same user group can cancel a resiliation and reopen the contract. 

cc/ @gva-acsone, @sbidoul , @pedrobaeza

### PR DESCRIPTION
**Pull request by sbejaoui**
Fixes: #458

### CODE REVIEW

**Review by gva-acsone — APPROVED** [review]
LGTM Functional review

**Review by dreispt — COMMENTED** [review]
Should the term "resiliation" be replaced with "termination"?
Other than that LGTM

**Comment by sbejaoui** [comment]
> Should the term "resiliation" be replaced with "termination"?
> Other than that LGTM

I am more with resiliation, a contract termination can be a normal use case when no auto-renew is set and all invoices were generated.

In this use case we would like to highlight this facts when customers expresses their wish to definitely end a contract
- Anticipated termination
- Invoicing stop at resiliation date
- Contract frozen unless an explicit action to remove the resiliation
- Auto-renew stop

**Comment by dreispt** [comment]
When a contract goes past it's expected end date, I would say it "expired".
"Termination" does mean a willful action to end something that was running, and IMO it matches the "resiliation" cases presented.
I'm not an English native, but looking up on an English dictionary [I can't find](https://dictionary.cambridge.org/spellcheck/english/?q=resiliation) the word "resiliation".

**Comment by sbejaoui** [comment]
> When a contract goes past it's expected end date, I would say it "expired".
> "Termination" does mean a willful action to end something that was running, and IMO it matches the "resiliation" cases presented.
> I'm not an English native, but looking up on an English dictionary [I can't find](https://dictionary.cambridge.org/spellcheck/english/?q=resiliation) the word "resiliation".

You convinced me, I will make the changes

**Comment by dreispt** [comment]
Thank for that!

**Review by dreispt — APPROVED** [review]

**Comment by dreispt** [comment]
@sbejaoui I think there is something missing. Can have a look at the build log?

**Comment by sbejaoui** [comment]
> @sbejaoui I think there is something missing. Can have a look at the build log?

it's fixed now

**Pull request merged**
