### PR TITLE
[IMP] contract: Migration script from 8.0 account_analytic_analysis

### PR DESCRIPTION
**Pull request by pedrobaeza**
WIP until https://github.com/OCA/openupgradelib/pull/63 is merged

### CODE REVIEW

**Comment by pedrobaeza** [comment]
cc @Tecnativa

**Comment by pedrobaeza** [comment]
This one is now ready to be reviewed

**Comment by ghost** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Merging optimistically as OpenUpgrade's policy

**Comment by ghost** [comment]
@pedrobaeza thanks

**Pull request merged**
