### PR TITLE
[IMP] contract_show_invoice: more lightweight solution

### PR DESCRIPTION
**Pull request by sbidoul**
In order to implement the button, it's not necessary to have a heavy stored computed field. So I propose to remove it.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Of course it looks good better! :+1: 

Can you propose the same for v9?

**Comment by sbidoul** [comment]
@pedrobaeza I removed the unneeded context from the action too.

I'll port it to v9 when this one is merged.

**Comment by sbidoul** [comment]
I also removed the test which was based on the unneeded computed field.

**Comment by sbidoul** [comment]
Runbot is red because of the missing xslxwriter python dependency

**Comment by jabibi** [comment]
Code review: it looks good for me. Clean and fresh according to new api :+1:

**Pull request merged**
