### PR TITLE
[WIP] add contract_payment_mode module

### PR DESCRIPTION
**Pull request by angelmoya**
WIP

adds module to set payment mode in contracts, to set on invoices

### CODE REVIEW

**Comment by angelmoya** [comment]
Runbot fails by a dependencie off bank payment, but I have already added to oca-dependencies.txt. Need I to do anymore?

**Comment by dreispt** [comment]
Stumbled upon the same problem. I think it's a bug: just opened an issue: https://github.com/OCA/maintainer-quality-tools/issues/274

**Comment by pedrobaeza** [comment]
@dreispt, it's not the same. Runbot dependencies have to be set manually. I have added it and restart build.

**Comment by angelmoya** [comment]
Please close this PR, I did it for branch 9.0 and module is for version 8.0

Module account_analytic_analysis is not present in version 9.0

**Pull request closed without merging**
