### PR TITLE
IMP: use group product.group_discount_per_so_line instead of base.gro…

### PR DESCRIPTION
**Pull request by damdam-s**
…up_no_one

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by petrus-v — APPROVED** [review]

**Comment by pedrobaeza** [comment]
There's not too much sense to add also optional of the field. Just don't add the user to the group instead.

**Comment by damdam-s** [comment]
@pedrobaeza I understand you point of view. However, some users in the group may not want to see the discount (for view simplification) and that's why I added the optional. 
Another reason is to match the optional of the discount_fixed field from #1009 but maybe I should add the optional part in the later PR.
Opinion?

**Comment by pedrobaeza** [comment]
OK, my only fear here is that someone hides the column, forget it, and then see that the subtotal is "incorrect" not seeing the discount, but it's not a big deal. Please rebase your branch to avoid merge commits though.

**Pull request merged**
