### PR TITLE
[WIP] [ADD] Make the time markers configurable on contact line

### PR DESCRIPTION
**Pull request by RoelAdriaans**
This module enables you do make the time on the contract lines configurable. 
For example, you can use #START(MMMM yyyy)# for times then you want to show only the starting month in the invoice line.

Feedback welcome, still not sure about the best way to document the options in the usage and view. This looks a but too much..

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please don't add plurals on module names. Maybe you can put this in the main module, as it can be a generic feature interesting for all users of contracts that use markers.

**Comment by RoelAdriaans** [comment]
@pedrobaeza I'll remove the plurals.

Main reason I've put this into a separate module is because it's a quite technical module, with  scary documentation. 
An option is to merge it into the main module, but put the extended documentation for the technical-group/debug mode?

**Comment by pedrobaeza** [comment]
> An option is to merge it into the main module, but put the extended documentation for the technical-group/debug mode?

Yeah, I like this option!

**Comment by RoelAdriaans** [comment]
Since I'm no longer working with Odoo, I'm abandoning this PR;

**Pull request closed without merging**
