### PR TITLE
[13.0][FIX] contract: Remove noupdate in mail template data

### PR DESCRIPTION
**Pull request by joao-p-marques**
@Tecnativa
TT29820

ping @pedrobaeza @carlosdauden

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You should remove it only for the qweb views, not for all.

**Comment by joao-p-marques** [comment]
Ok, I had to separate it in 2 files, was that what you meant?

**Comment by pedrobaeza** [comment]
Not really. You can put several `<data>` sections in the same file. The requirement is to have the common ancestor `<odoo>` in that case. Anyways, we usually split files by model, so it's not bad to move the others to `views/template_....xml`.

**Comment by joao-p-marques** [comment]
Ok, thanks @pedrobaeza 

Changes made

**Review by pedrobaeza — APPROVED** [review]
Usual path is in `templates` or in `views` (see https://github.com/OCA/maintainer-tools/tree/master/template/module/templates), but let's continue as it's a minor detail.

**Review by chienandalu — APPROVED** [review]

**Pull request merged**
