### PR TITLE
[14.0][ADD] contract_sale: Add tests to the module

### PR DESCRIPTION
**Pull request by JoanMForgeFlow**
Added tests to the module in version 14.0, depends on: https://github.com/OCA/contract/pull/763
@BernatPForgeFlow 
@mariadforgeflow
@AaronHForgeFlow 
@LoisRForgeFlow

### CODE REVIEW

**Review by BernatPForgeFlow — APPROVED** [review]
LGTM!

**Review by mariadforgeflow — APPROVED** [review]
LGTM:)

**Review by AaronHForgeFlow — APPROVED** [review]

**Review by AaronHForgeFlow — CHANGES_REQUESTED** [review]
Test failing:

```
----------
ERROR: setUpClass (odoo.addons.contract_sale.tests.test_sale_contract.TestContract)
Traceback (most recent call last):
  File "/home/travis/odoo-14.0/odoo/tests/common.py", line 173, in _handleClassSetUp
    setUpClass()
  File "/home/travis/build/OCA/contract/setup/contract_sale/odoo/addons/contract_sale/tests/test_sale_contract.py", line 12, in setUpClass
    cls.user_sales_all_documents = cls.env["res.users"].create(
AttributeError: type object 'TestContract' has no attribute 'env'
```

**Comment by AaronHForgeFlow** [comment]
Not it fails because of this:
```
  File "/home/travis/odoo-14.0/odoo/addons/base/models/ir_model.py", line 1805, in check
    raise AccessError(msg)
odoo.exceptions.AccessError: You are not allowed to create 'Contract Modification' (contract.modification) records.
This operation is allowed for the following groups:
	- Invoicing/Billing
Contact your administrator to request access if necessary.
```

Waiting for [this PR](https://github.com/OCA/contract/pull/763)

**Comment by AaronHForgeFlow** [comment]
Perhaps you can include the commit of the other PR here. WDYT?

**Comment by JoanMForgeFlow** [comment]
> Perhaps you can include the commit of the other PR here. WDYT?

this https://github.com/OCA/contract/pull/763 has been merged, now its green.

**Review by GuillemCForgeFlow — APPROVED** [review]
LGTM! :smile:

**Review by AaronHForgeFlow — APPROVED** [review]

**Pull request merged**
