### PR TITLE
[16.0][MIG] contract_sale: Migration to 16.0

### PR DESCRIPTION
**Pull request by urvisha-serpentcs**

### CODE REVIEW

**Comment by urvisha-serpentcs** [comment]
Maybe test cases fail because of the contract module dependency, we have open PR of the contract module https://github.com/OCA/contract/pull/887 if we merge first then test cases fails is solved

**Review by manuelcalerosolis — COMMENTED** [review]
Functional review ok!

**Comment by pedrobaeza** [comment]
Please rebase to see the proper CI status.

**Comment by rousseldenis** [comment]
@urvisha-serpentcs Do you mind if we switch to #949 ?

**Comment by urvisha-serpentcs** [comment]
@rousseldenis you can switch

**Pull request closed without merging**
