### PR TITLE
10.0  [MIG] Migration to V10 / [UPD] Update translation DE

### PR DESCRIPTION
**Pull request by lucode**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please respect commit history following migration guide https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

**Comment by pedrobaeza** [comment]
But you have to preserve commit history. Please see specifically this procedure: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0#technical-method-to-migrate-a-module-from-90-to-100-branch

**Comment by lucode** [comment]
Sorry that part of the procedure i did miss. I don't know how to procede exactly now. As I have already forked to repo to my private one, is see some conflicts arising. Shall I just delete that contract repo and start again?
Is this correct in the Technical method section it is described to directly clone the repo from OCA and then to commit the updated version to ones one repo. But normally I fork the repo to my private repo first and clone it from there. 
```
$ git clone https://github.com/OCA/contract -b 10.0
$ git checkout -b 10.0-mig-contract_digitized_signature origin/10.0
```

**Comment by pedrobaeza** [comment]
What I recommend is:

* Save your modified files in any place.
* Remove the branch in your local.
* Start the procedure from the beginning, but calling the branch the same name as now (although it's not the best name, as you have it as `10.0`, but the idea is to preserve the PR). If not, just close this PR.
* When done with the procedure, copy the modified files over.
* Make a new commit for the migration.
* Upload the branch.

**Pull request closed without merging**
