### PR TITLE
[16.0][MIG] agreement_rebate_partner_company_group: Migration to version 16.0

### PR DESCRIPTION
**Pull request by stefan-tecnativa**
cc @Tecnativa TT44313

This PR depends on https://github.com/OCA/agreement/pull/21

@CarlosRoca13 @chienandalu please review!

### CODE REVIEW

**Review by CarlosRoca13 — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]
Tested :+1:

**Review by carlosdauden — APPROVED** [review]
Code LGTM

**Review by chienandalu — APPROVED** [review]
Tested and working fine :+1:

**Pull request merged**
