### PR TITLE
[FIX+IMP] contract: Fixes #125 + multi-company

### LINKED ISSUE #125: [10.0][BUG][contract] No way to create a contract
- Go to runbot http://3310680-10-0-ed75c2.runbot2.odoo-community.org/web
- Go to Accounting / invoice -> Contract
- Try to create a contract

You will get this:

### PR DESCRIPTION
**Pull request by lasley**
* Add company_id to account and contract views to fix #125

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@lasley the problem was not that. I have added a commit to your PR for a real fixing. See my commit message for further explanation:

* company_id was empty because an onchange, not inheritance nor visibility
* Added multi-company group to company_id fields
* Added multi-company access rule to contract templates
* Fix double %% in XML dates that was causing an error
* When creating a contract, recurring_invoices is set by default

With this, all the multi-company is also covered in the module (it wasn't too difficult, eh! :wink: )

**Review by carlosdauden — APPROVED** [review]
LGTM

**Review by lasley — COMMENTED** [review]
Thanks for the fix @pedrobaeza - my Runbot was effed yesterday, so I blindly submitted this one and forgot to come back to test. 

👍  from me, I just can't review my own PR.

Are you OK with both of these commits being squashed together? I feel like my commit is pretty useless for history given your's.

**Comment by pedrobaeza** [comment]
OK, we can squash both keeping the correct commit message.

**Comment by lasley** [comment]
Done & amended so you're the proper author.

**Comment by pedrobaeza** [comment]
Merging as the Travis error is unrelated and this is critical for making the module worked correctly

**Pull request merged**
