### PR TITLE
[FIX]contract: In Progress state search

### PR DESCRIPTION
**Pull request by manuelregidor**
'In Progress' state search not showing all the In Progress lines.

### CODE REVIEW

**Comment by ValentinVinagre** [comment]
@HaraldPanten

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Review by ValentinVinagre — APPROVED** [review]

**Comment by manuelregidor** [comment]
@AaronHForgeFlow Can you have a look, please?

**Review by AaronHForgeFlow — APPROVED** [review]
Code review LGTM

**Comment by ValentinVinagre** [comment]
@dreispt could you review?

**Comment by ValentinVinagre** [comment]
@AaronHForgeFlow Could you merge it?

**Pull request merged**
