### PR TITLE
[13.0] [MIG] agreement sale

### PR DESCRIPTION
**Pull request by i-vyshnevska**
migrate agreement sale
related to https://github.com/OCA/contract/pull/397

### CODE REVIEW

**Comment by max3903** [comment]
@i-vyshnevska Please have a look at #386

**Review by TDu — APPROVED** [review]

**Review by jgrandguillaume — APPROVED** [review]
Works well on functional side

**Comment by dreispt** [comment]
There is a code formatting issue preventing a green build:
https://travis-ci.org/github/OCA/contract/jobs/602255402#L295

**Pull request merged**
