### PR TITLE
[FIX] contract: Fix migration script

### PR DESCRIPTION
**Pull request by sergio-teruel**
12.0.4.0.0 Fix migration script
@pedrobaeza Can you take a look??

### CODE REVIEW

**Comment by pedrobaeza** [comment]
AFAIK this is not needed. What is the problem?

**Comment by sergio-teruel** [comment]
This is de error:
`  File "contract/migrations/12.0.4.0.0/pre-migration.py", line 133, in migrate
    create_contract_records(cr)
  File "contract/migrations/12.0.4.0.0/pre-migration.py", line 101, in create_contract_records
    sql.Identifier(contract_field_name),
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib/openupgrade.py", line 934, in logged_query
    logger.debug('Running %s', query % args)
TypeError: unsupported operand type(s) for %: 'Composed' and 'tuple'
`

**Comment by pedrobaeza** [comment]
I think you don't have latest openupgradelib version. Please try with latest.

**Comment by sergio-teruel** [comment]
Ok. tested with new version...  So I close it. 
Thanks

**Pull request closed without merging**
