### PR TITLE
[MIG][13.0] contract_variable_qty_timesheet: Migration to 13.0

### PR DESCRIPTION
**Pull request by flachica**

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Let's fast-track it as straight-forward:

/ocabot merge nobump

**Comment by pedrobaeza** [comment]
@flachica, please rebase and fix the pre-commit errors that weren't there when you did the PR.

**Comment by flachica** [comment]
> @flachica, please rebase and fix the pre-commit errors that weren't there when you did the PR.


Mr. Travis returned to green dear Baeza

**Pull request merged**
