### PR TITLE
[10.0] [FIX] contract. Optimize insertion of dates in invoice and lines.

### PR DESCRIPTION
**Pull request by NL66278**
Try to prevent repetition of date and date format computation, with i/o to language table, for every contract line, while the computation is needed only once per contract.

### CODE REVIEW

**Comment by NL66278** [comment]
Actually refactoring the setting of the context, also allows for further optimizations by disabling mail tracking, this is not part of the PR because that would be a functional change, but in our customization we have:
```
    @api.multi
    def get_invoice_context(self):
        """Compute context for invoice creation."""
        self.ensure_one()
        ctx = super(AccountAnalyticAccount, self).get_invoice_context()
        ctx['tracking_disable'] = True
        return ctx
```

**Comment by pedrobaeza** [comment]
Do you gain too much performance with this? I remember this was done on purpose for overwriting the method and alter the description got. @carlosdauden do you remember why?

**Comment by NL66278** [comment]
@pedrobaeza Actually we do gain performance. To be true, it has an extra effect for us, as we also use the _insert_markers method for the invoice name, not only on the lines. But a lot of processing duplication is saved if you have multiple lines anyway.

I have done some profiling. And created an image of the results with gprof2dot:
```
gprof2dot -n 4.0 -f pstats invoice_cron.profile | dot -Tpng -o output.png
```
I have a before image and the final output. The before image was on 76 records, the final on 84. The difference includes the fact that we have also overriden get_invoice_context to disable mail tracking.
invoice_cron profile-before1

After changes:
output

**Comment by pedrobaeza** [comment]
OK, it's hard to read that wide graph, but I trust if you say so. No blocking by my side.

**Comment by rafaelbn** [comment]
@NL66278 could you please resolve conflicts ?

**Comment by rafaelbn** [comment]
Related? https://github.com/OCA/contract/pull/218

**Review by yajo — APPROVED** [review]
It seems a pretty intelligent enhancement. Thanks!

**Comment by pedrobaeza** [comment]
There are conflicts

**Comment by NL66278** [comment]
@rafaelbn Yes this is related to #218. Actually an alternative approach to the same performance problems. So if this solution is sufficient and accepted, we might not need #218  any more.

**Comment by NL66278** [comment]
@pedrobaeza @rafaelbn Conflicts have been resolved.

**Comment by yajo** [comment]
IMHO, (without actually running performance tests, just by reading code), it seems like this patch covers more possible bottlenecks in a more scalable way than #218.

**Review by rafaelbn — APPROVED** [review]

**Comment by rafaelbn** [comment]
Sorry for the noise @sbejaoui but you could have a similar situation of this

**Pull request merged**
