### PR TITLE
[10.0] contract: allow to limit records on cron

### PR DESCRIPTION
**Pull request by chienandalu**
Allow to create process de recurring invoices in batches in case there are many contracts.

cc @Tecnativa

### CODE REVIEW

**Comment by chienandalu** [comment]
ping @Yajo

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
This technique doesn't serve as some of the contracts might not be invoiceable, but are ignored by this line:

https://github.com/OCA/contract/pull/260/files#diff-47b79491db78ebebcb372014ce9c7bf3R274

so maybe you have more than these contracts than the limit set.

**Comment by yajo** [comment]
Fixed.

I realized that, if somebody wanted to use this, updates would revert his change, because the cron wasn't noupdate, so I took the chance to give a sane non-blocking default and still setting it as noupdate to avoid updates to break the admin's choice.

**Review by yajo — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Thinking again, I prefer to not change cron behavior, as it was intended for generating all invoices the same day. With this, you won't have them if you have more than limit * 24 invoices. This is patching a problem in other place, so it shouldn't be the default.

**Comment by yajo** [comment]
OK, fixed.

**Comment by pedrobaeza** [comment]
There are conflicts

**Comment by yajo** [comment]
Fixed.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
