### PR TITLE
[12.0][FIX] contract: Allow showing contract lines for contracts

### PR DESCRIPTION
**Pull request by hbrunn**
this gets us some simple statistics easily by filtering/grouping the resulting list

### CODE REVIEW

**Review by flotho — COMMENTED** [review]
Hi,
Thanks for the proposal,
how this action is used in the main code?
I can't see no menu nor python code nor views referencing this action.

**Comment by hbrunn** [comment]
https://github.com/OCA/contract/pull/707/files#diff-1512a6ffc6e6a949a2fa73890a73f8a5b5628511348c374cfa7ad0780ba7e144R184 causes the action to show up in the action menu of list views

**Review by flotho — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]

**Comment by rousseldenis** [comment]
@hbrunn FYI I did this for v14: https://github.com/OCA/contract/pull/831

**Pull request merged**
