### PR TITLE
Added correct domain for supplier contract's on payment mode

### PR DESCRIPTION
**Pull request by vinclar**
Added view for supplier contracts, respecting the domain for payment_type. 
Before was showing the inbound types in the supplier payment

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please check why Travis is red

**Review by dreispt — APPROVED** [review]
LGTM

**Comment by pedrobaeza** [comment]
Please squash commits.

**Comment by dreispt** [comment]
@pedrobaeza that's a nitpick that will ensure this will stay open forever. The PR was not even made using Git, but through Github UI.

**Comment by pedrobaeza** [comment]
If he want it merged, it's very easy to be done. What we can't do is to have a very dirty commit history due to laziness of the original contributor. I'm going to oppose always for something like that.

**Comment by pedrobaeza** [comment]
Note that even the initial commit title is not correct, but I'm not being too much picky for also asking for that.

**Comment by dreispt** [comment]
Superseded by #483

**Pull request closed without merging**
