### PR TITLE
[11.0] [MIG] contract_sale_generation

### PR DESCRIPTION
**Pull request by levkar**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you please fix the PR as it involves other files that are not the mentioned module?

**Comment by rafaelbn** [comment]
Hello! Thanks for this contribution @levkar !

Could you please resolve conflicts? "This branch has conflicts that must be resolved"

**Comment by levkar** [comment]
Hello.
How do i resolve these conflicts? I followed the migration guidelines. I can close this and send another pr.

**Comment by pedrobaeza** [comment]
It seems your PR is modifying some files that are not of your changes (see conflicting files). You can start again the procedure and make sure you only fetch changes for the module you want to migrate.

**Comment by pedrobaeza** [comment]
Is this going to be continued?

**Comment by rafaelbn** [comment]
Hello, I close as no answer from @levkar

**Pull request closed without merging**
