### PR TITLE
[IMP] agreement 11.0.0.1.0

### PR DESCRIPTION
**Pull request by max3903**
#216

### CODE REVIEW

**Review by bodedra — APPROVED** [review]
@max3903 Menu items (Recitals, Appendices and Service Profiles) are visible under _"Master Data"_ not _"Master Data > Content"_ So do we need to improve it ? Other than that LGTM :+1:

**Review by smangukiya — APPROVED** [review]
@max3903 : Source changes looks ok to merge. And yes agree with @bodedra on menu thing minor change.

**Comment by max3903** [comment]
@smangukiya I didn't have the time yesterday to do the items on #216 related to the dynamic values. Can you take care of it please?

**Comment by smangukiya** [comment]
> @smangukiya I didn't have the time yesterday to do the items on #216 related to the dynamic values. Can you take care of it please?

@max3903 : Yes, I am on it.

**Comment by smangukiya** [comment]
@max3903 : I guess, we are missing master data menu for agreement.increasetype object action?

**Comment by max3903** [comment]
@smangukiya increase type should be in the configuration submenu with renewal type.

**Comment by max3903** [comment]
Merging. The remaining can go in a separate PR.

**Pull request merged**
