### PR TITLE
[15.0][MIG] product_contract

### PR DESCRIPTION
**Pull request by adasatorres**
#732

### CODE REVIEW

**Comment by Rad0van** [comment]
See #950 @rousseldenis has had comments that I believe are applicable here as well (onchange vs compute mainly)

**Comment by nileshsheliya** [comment]
@adasatorres I just check functionality, for sale order line form, it show dangling checkbox. Can we show it below Product with label.
image (32)

**Comment by Rad0van** [comment]
> See #950 @rousseldenis has had comments that I believe are applicable here as well (onchange vs compute mainly)

Sorry, I meant #959

**Comment by pcastelovigo** [comment]
> @adasatorres I just check functionality, for sale order line form, it show dangling checkbox. Can we show it below Product with label. image (32)

Perfect now, hopefully its merged

**Comment by pedrobaeza** [comment]
Merging for not losing the migration

/ocabot merge nobump

**Pull request merged**
