### PR TITLE
[14.0][MIG] agreement_mrp

### PR DESCRIPTION
**Pull request by Vimal-OSI**

### CODE REVIEW

**Comment by patrickrwilson** [comment]
@Vimal-OSI can you please squash bot commits in history?

**Comment by Vimal-OSI** [comment]
> @Vimal-OSI can you please squash bot commits in history?

@patrickrwilson , Done

**Review by patrickrwilson — APPROVED** [review]
Tested and works. LGTM

**Comment by Vimal-OSI** [comment]
@patrickrwilson ping.

**Review by dsolanki-initos — APPROVED** [review]
Code review. LGTM

**Comment by dsolanki-initos** [comment]
@dreispt Can we merge this ?

**Pull request merged**
