### PR TITLE
[15.0] [MIG] agreement_legal

### PR DESCRIPTION
**Pull request by davidmonterocrespo24**

### CODE REVIEW

**Comment by davidmonterocrespo24** [comment]
@rousseldenis 
@max3903 
@mvrodriguez 
@marylla 

Hello, I am interested in contributing to this repository, but I see that my merge request did not pass some tests. Could you help me? 
Best regards

David Montero

**Comment by max3903** [comment]
@davidmonterocrespo24 The pre-commit errors are listed here:
https://github.com/OCA/contract/actions/runs/3304920162/jobs/5454664883

and the tests results are here:
https://github.com/OCA/contract/actions/runs/3304920161/jobs/5454664886#step:8:68

Does it help get you going?

**Comment by rousseldenis** [comment]
@davidmonterocrespo24 @max3903 Since 15.0, agreement repository exists : https://github.com/OCA/agreement

And this module is merged

**Comment by davidmonterocrespo24** [comment]
Hello @rousseldenis 
I did not know that these modules had been separated from the repository
Thank you
Best regards

**Comment by max3903** [comment]
So I guess the plan to merge agreement with contract failed... #386

**Comment by rousseldenis** [comment]
> So I guess the plan to merge agreement with contract failed... #386

That would not refrain basing some modules on top of others. But nobody has pointed out a need at this time (apart Alexis, but did it on his side)

**Pull request closed without merging**
