### PR TITLE
[PRODUCT_CONTRACT] - add auto_renew_interval, auto_renew_rule_type fields to sale order line

### PR DESCRIPTION
**Pull request by sbejaoui**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
For me all this renewal stuff should be hidden under a configuration group for handling renewals, as this doesn't interest to most people using contracts.

**Review by dreispt — APPROVED** [review]
LGTM
The related options are hidden until the auto-renew flag is turned on, so I thin @pedrobaeza concerns are addressed.

**Review by gva-acsone — APPROVED** [review]
LGTM

**Pull request merged**
