### PR TITLE
[13.0][FIX] contract: Avoid error in invoicing contracts crone (forward port)

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Forward port of https://github.com/OCA/contract/pull/739.

### CODE REVIEW

**Review by dreispt — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Why not including such conditions in the domain?

**Review by ajaniszewska-dev — APPROVED** [review]

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Why not including such conditions in the domain?

**Comment by MiquelRForgeFlow** [comment]
> Why not including such conditions in the domain?

Because I was just cherry-picking a commit, not refactoring that commit.

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Let's do it better on newer versions:

/ocabot merge patch

**Comment by MiquelRForgeFlow** [comment]
Forward port done in https://github.com/OCA/contract/pull/755.

**Comment by pedrobaeza** [comment]
Sorry for the noise. The condition can't be put as domain. Trying to merge again the original patch:

/ocabot merge patch

**Comment by pedrobaeza** [comment]
It's a pre-commit reformat that you have to include in your commit.

**Comment by MiquelRForgeFlow** [comment]
Yeah, I went too fast doing the revert hehe. Now it's correct! :)

**Pull request merged**
