### PR TITLE
[11.0][RM] agreement_fsm module

### PR DESCRIPTION
**Pull request by bodedra**
Issue Reference: https://github.com/OCA/contract/issues/231

### CODE REVIEW

**Review by etobella — APPROVED** [review]
LGTM :+1:

**Review by pedrobaeza — APPROVED** [review]
There's no need of removing postgres version, but it's not a requirement any way for this version.

**Comment by bodedra** [comment]
Thank you @pedrobaeza I have added that lines at https://github.com/OCA/contract/pull/229/files so I have removed it and there will be no chance to fail again. ;-)

**Comment by pedrobaeza** [comment]
Well, there has been an error, as field-service is still used in agreement_maintenance, but I have re-added the dependency in oca_dependencies.txt, although I think we might move that one also to OCA/field-service.

**Comment by pedrobaeza** [comment]
There are still problems with the CI, as by dependencies geospatial is trying to be installed and there's an error on that:

https://travis-ci.org/OCA/contract/jobs/466071710#L756

Possibilities:

1. Fixed .travis.yml for avoiding this problem.
2. Remove `agreement_maintenance`.

**Comment by max3903** [comment]
@bodedra Let's go with option 2 for now.

**Pull request merged**
