### PR TITLE
[NEW] contract_sale_generation_warehouse: to 16.0

### PR DESCRIPTION
**Pull request by NotJaime13**
New module extends functionality of sale contracts to be able select any warehouse.

### CODE REVIEW

**Comment by rousseldenis** [comment]
@NotJaime13 Thanks for this. Looks great.

If you want reviewers being able to test this, you can follow this guide to embed unmerged PRs : https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference%28s%29-to-another-pull-request%28s%29

**Review by NotJaime13 — COMMENTED** [review]
Functional review ok!

**Comment by rousseldenis** [comment]
@NotJaime13 Could you please remove the commits coming from other modules ?

**Review by manuelcalerosolis — COMMENTED** [review]
Functional review ok!

**Pull request closed without merging**
