### PR TITLE
[10.0] [FIX] contract: Make sure tests don't fail on other languages

### PR DESCRIPTION
**Pull request by NL66278**
Make sure tests do not fail because of missing sale journal.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
What is the use case where you don't have journal? CoA not installed?

**Comment by NL66278** [comment]
We have encountered this in our own runbot instances. Also the tests would fail for buildouts based on another language than en_US. So these changes decrease the amount of assumptions the test makes about the environment in which the tests are run.

**Comment by pedrobaeza** [comment]
But you will have the same problem with accounts, so adding this bunch of code is a lot. You should fix your test process instead, setting for example an initial country in your DB.

**Comment by NL66278** [comment]
We set nl_NL in our database. That is why the test based on a journal description (which assumes English always) was not working. Also the tests for the contract module are run before our custom chart of account is installed, which is logical because our custom modules are based on OCA or Odoo modules, not the other way around obviously.

**Comment by pedrobaeza** [comment]
I don't see where is the "test based on a journal description". Can you point me to it? I see better to make the test more resilient to that than to create the journal disconnected from the rest.

**Comment by NL66278** [comment]
Sorry it is not a journal description but the line name compared with the product name in line 267 of the existing code.

**Comment by pedrobaeza** [comment]
OK, that patch is correct, but the conflicting one is the journal manual creation.

**Comment by pedrobaeza** [comment]
I have change the title to the most suitable one. Are you going to fix this?

**Comment by NL66278** [comment]
@pedrobaeza Maybe we still have a different view on the need or not of having the tests independent of Chart of Account installation.

The travis errors are due to a timeout in another module. I will look into that next monday.

**Comment by pedrobaeza** [comment]
It's not a different vision, but simply that with your approach, integration tests doesn't work correctly, as no chart account is possible to be installed having your extra stuff

**Comment by NL66278** [comment]
@pedrobaeza Maybe I misunderstand you. I do not quite see how my extra stuff (the creation of a journal) would prevent installation of a chart of accounts. Especially not because the data / records added by the test will be automatically rolled back when the test is finished.

**Comment by pedrobaeza** [comment]
You are right about the rollback, but I remember one collision doing something similar one time. OK, let's greenify this and merge, and will see if there's a problem in the future.

**Comment by rafaelbn** [comment]
Hello, could we update this PR? conflicts + travis :red_circle:  please! thanks a lot!

**Comment by NL66278** [comment]
Travis errors seem to be unrelated. Problem with mailing invoice from another module.

**Comment by yajo** [comment]
Hi there @NL66278. I fought in the past with your exact same problem. :disappointed:  When you get to fix the accounting in foreign language problem, your'e gonna start seeing lots of other tests breaking. Some of them just can't be written in other form, like i.e. the website tours (which need for instance the product names in English). The same can happen when moving tests to post mode to make them run fine on your custom addons; you'll find some folks here at OCA rolling back your changes and you can't do anything about it because, after all, they're right.

So, basically, run tests in English or you'll enter an endless rabbit hole that will lead you to... :rabbit: run your tests in English :smile:. I've been there too.

Alternatives that will make you sleep better:

- Enable `l10n_generic_coa` in your CI envs, although it's not present in production ones.
- Disable, or defer to a later step, testing country-specific addons. Usually the dependency chain handles that.
- You can `from odoo.addons.contract.tests.test_contract import TestContractBase` and extend it in your own CoA to adapt it to your custom needs, so you actually test your CoA too.

I have a feeling this patch is going to break more things that fix. Would any of these strategies (or another one you can think of) work for you?

Also, **Travis' :x: comes from this PR** (main branch is :heavy_check_mark:). Possibly an unclosed cursor from the `setUpClass` of a `SavepointCase`. It's a nasty bug that I've hit many times.

**Comment by NL66278** [comment]
@Yajo we are running our tests in English. Although the default language of most of our buildouts is Dutch, we always switch the administrator to English. A few test will still fail then, but we have patched Odoo to run these correctly as well (see: https://github.com/nl66278/odoo/tree/10.0-delete-some-tests).

However the main point of this PR is not the language, but to run the tests after all modules have installed, and to run them independently of wether or not there already is a journal created.

Travis is red because the test for one other module reach out to the internet with a http request that timed out. I really think tests that are dependent on external services should not be part of a global integration test like runbot.

**Comment by pedrobaeza** [comment]
> Travis is red because the test for one other module reach out to the internet with a http request that timed out. I really think tests that are dependent on external services should not be part of a global integration test like runbot.

On that, I don't agree, as if a module integrates an external service, you have to test that it works, and that can only be done testing with the real external service. Mocking and so on is cheating. For example, `base_location_geonames_import` must connect to Geonames.org to download a file and test the proper import, or if the format of the file has changed, then the module becomes unuseful as it won't work when using it in real life.

**Comment by NL66278** [comment]
@pedrobaeza I am not saying those modules should not be tested, just that they should not be tested as part of an integral tests of all the modules in a repository (in addition to all the Odoo modules) that can together depend on lots of external services, the non availability of any of them causing a travis failure that is unrelated to the actual changes in the PR.

**Comment by yajo** [comment]
> to run the tests after all modules have installed, and to run them independently of wether or not there already is a journal created

If the test works no matter if there is or not a journal installed, then why do you need to move it to post install mode? :thinking:

**Comment by pedrobaeza** [comment]
Again I don't agree. The combination of several modules in an specific installation might make them to fail, and you need to check that. If not, your conditions won't be reproducible. Scientific method: always recreate all the variables of the experiment.

**Comment by NL66278** [comment]
@Yajo The post install is to test it in combination with all the other modules to be installed. On that I fully agree with the last commit by @pedrobaeza .

**Comment by NL66278** [comment]
@pedrobaeza I have no specific proposal for now on how to actually run the tests with the externally dependent tests left out. So pushed my branch again to force a new Travis run. I agree on scientist reproducing tests while keeping all variables under control. We just don't control the external variables. So it is like doing research into the growth of bacteria with the windows open, instead of in a clean room.

**Comment by yajo** [comment]
> The post install is to test it in combination with all the other modules to be installed

But the test is stateless now, isn't it? Other modules shouldn't affect it.

Relying in random modules installed or not is somehow like relying in external network access: not reproducible.

I think that the main problem is that Odoo lacks a proper integration testing framework, so we tend to use unit tests for integration tests. OCA should provide a solution on _that_ matter. :thinking:

**Comment by rafaelbn** [comment]
Do we agree something here? Thanks. Travis is :red_circle:

**Comment by yajo** [comment]
I guess the problem is the PR title, which is misleading because the fix has nothing to do with languages.

The fix is OK, but it should be in at-install mode and travis should be green.

**Pull request closed without merging**
