### PR TITLE
[IMP] contract: add kanban, calendar, graph, pivot, activity views on contract

### PR DESCRIPTION
**Pull request by len-foss**

### CODE REVIEW

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Review by sbejaoui — APPROVED** [review]
Thanks

**Comment by sbejaoui** [comment]
It will be nice to forward-port it

**Comment by len-foss** [comment]
Thanks @sbejaoui 
https://github.com/OCA/contract/pull/704
I'll check it on runbot once it's up. Also I haven't checked too much the default parameters, I wanted to have something so that the views are at least there.

**Pull request merged**
