### PR TITLE
[IMP] agreement_serviceprofile (Search)

### PR DESCRIPTION
**Pull request by patrickrwilson**
Added a few fields to the search view

### CODE REVIEW

**Comment by patrickrwilson** [comment]
ping @max3903 @osi-scampbell

**Comment by patrickrwilson** [comment]
@max3903 @osi-scampbell can you review this PR please?

**Comment by osi-scampbell** [comment]
@patrickrwilson I haven't been marked as a reviewer but it LGMT

**Review by bodedra — APPROVED** [review]
LG :+1:

**Review by marcelsavegnago — APPROVED** [review]

**Pull request closed without merging**
