### PR TITLE
[16.0][MIG] subscription_oca: Migration to 16.0

### PR DESCRIPTION
**Pull request by carolina-domatix**

### CODE REVIEW

**Comment by chrisandrewmann** [comment]
Hi @carolina-domatix 
Thanks for the migration. I've just tested it and I think the tests were failing because of these 2 lines.

https://github.com/carolina-domatix/contract/blob/ed5f7910b52bf0d482d46fba8c9575bb4924a064/subscription_oca/models/sale_subscription_line.py#L100C21-L100C21

Suggested Correction:
`line.sale_subscription_id.partner_id`

https://github.com/carolina-domatix/contract/blob/ed5f7910b52bf0d482d46fba8c9575bb4924a064/subscription_oca/models/sale_subscription_line.py#L266

Suggested Correction:
`).list_price`

**Comment by bvanjeelharia** [comment]
> https://github.com/carolina-domatix/contract/blob/ed5f7910b52bf0d482d46fba8c9575bb4924a064/subscription_oca/models/sale_subscription_line.py#L266

The correction here should be
`return self.sale_subscription_id.pricelist_id._get_product_price(product, uom=self.product_id.uom_id,
                                                                             quantity=self.product_uom_qty or 1.0)`

**Comment by bvanjeelharia** [comment]
> https://github.com/carolina-domatix/contract/blob/ed5f7910b52bf0d482d46fba8c9575bb4924a064/subscription_oca/models/sale_subscription_line.py#L266

The correction here should be:
`return self.sale_subscription_id.pricelist_id._get_product_price(product, self.product_uom_qty or 1.0,
                                                                             uom=self.product_id.uom_id)`

**Review by flotho — CHANGES_REQUESTED** [review]
Hi,

I've tested on the runboat the process.
I used a template with sale order and invouce option
Once I clicked on create invoices, I have only invoices.
Is it normal, is there any additionnal process or documentation to provide for this use case ?
Anyway, thanks for the great job

**Comment by carolina-domatix** [comment]
Thank you for your help @chrisandrewmann and @bvanjeelharia!

Hi @flotho, the "sale order and invoice" option is triggered through the subscription manager cron (cron_subscription_manager), while the "create invoice" button is used to create an invoice manually.

**Comment by flotho** [comment]
Hi @carolina-domatix thanks for your answer.
Any chance to precise it in the readme https://github.com/OCA/contract/pull/1029/files#diff-402d3781a6918fc5c5c7a839b628847fd6cfc369bd0ac25b7099ae49f085c52bR46 ?

**Review by flotho — APPROVED** [review]
thanks for changes
LGTM

**Comment by flotho** [comment]
ping @gaelTorrecillas + @DorianMAG @JulienMartinez

**Review by gaelTorrecillas — APPROVED** [review]

**Comment by DorianMAG** [comment]
Hi @carolina-domatix 
Great job, thx !
Maybe a miss something, but i can't add product in template subscription.
Can you explain us, how to proced plz?
Regards

**Comment by DorianMAG** [comment]
> Hi @carolina-domatix Great job, thx ! Maybe a miss something, but i can't add product in template subscription. Can you explain us, how to proced plz? Regards

Oh sorry, i finally find it,
very simple, configuration in sale tab product.
Regards

**Review by DorianMAG — APPROVED** [review]
Tested in runboat,
LGTM

**Comment by flotho** [comment]
Hi @simahawk  @gurneyalex @dreispt 
As your mentionned as representative here https://oca.github.io/repo-maintainer-conf/teams.html#project-service-maintainers-psc-representative I'm wondering if it's the proper way to have your attention on merging this PR.
Sorry for disturbance if the process is not appropriate.
Regards

**Pull request merged**
