### PR TITLE
[12.0][FIX] contract: correct relation of old_contract_id

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
If you have an account.analytic.account without contract line, then the contract is not ported to new table contract_contract. And then, old_contract_id of account_invoice, as now will point to contract.contract, happens that will point to a non-existing contract. Odoo detects that and breaks.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I would prefer to merge the contract in that case as inactive. In fact, there was some code for that if I recall correctly.

**Review by LoisRForgeFlow — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
@pedrobaeza 
image
You only make inactive if not recurring_invoices

**Comment by pedrobaeza** [comment]
Then expand that to cover such situation

**Comment by MiquelRForgeFlow** [comment]
But that would be fake inactive contracts.

**Comment by pedrobaeza** [comment]
Why they are fake? If there's an invoice with such relation, it has been a contract in a moment in time.

**Comment by MiquelRForgeFlow** [comment]
@pedrobaeza done

**Comment by MiquelRForgeFlow** [comment]
and green

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
