### PR TITLE
[12.0][IMP] contract : show tags with colors in the contract

### PR DESCRIPTION
**Pull request by chandni299**

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
LGTM

**Review by marylla — APPROVED** [review]
I made a functional review. LGTM. :+1: 

I can see the colored tags in form and tree view.

**Comment by marylla** [comment]
@rousseldenis Can you merge this one for Odoo 12 and these for newer Odoo versions #860 #861 #862.

**Comment by marylla** [comment]
@pedrobaeza Hi Pedro, would you be so kind to merge this PR? You've already merged it for the higher Odoo versions... :)

**Pull request merged**
