### PR TITLE
[12.0][MIG] agreement

### PR DESCRIPTION
**Pull request by ygol**

### CODE REVIEW

**Comment by ygol** [comment]
Hi @max3903.
1. Regarding Issue #216: Wouldn't be better to first migrate and then add those new fields?
2. I created 1 PR per module. Here's the first module.
3. There's an error in the log:

> Invalid view Agreement Kanban definition in agreement/views/agreement.xml

but the kanban seem to function alright. There are also few warnings about same labels used twice.
kindly advise

**Comment by max3903** [comment]
Hello @ygol,

1. I have no date yet as to when we will add those fields in v11, so yes we can proceed that way.
2. :+1: 
3. Please look at https://travis-ci.org/OCA/contract/jobs/460800412#L1211. Regarding the labels, I don't have a better option. The description warnings can be easily fixed.

Thank you for your patience.

**Comment by max3903** [comment]
@ygol We need the original history from v11.

Please have a look at the documentation on how to do that:
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0#howto

Thanks!

**Comment by ygol** [comment]
> 
> 
> @ygol We need the original history from v11.
> 
> Please have a look at the documentation on how to do that:
> https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0#howto
> 
> Thanks!

so I close this PR and start over?

**Comment by max3903** [comment]
@ygol You can keep this PR: while you go through the steps, you can push to that same branch.

**Pull request closed without merging**
