### PR TITLE
[14.0][FIX] agreement_legal_sale - ignore sale order lines with display_type

### PR DESCRIPTION
**Pull request by ghost**
When confirming a sale order with an agreement template and the order has some lines that are not product lines, you have an error message about missing uom because it tries to create lines for the note/section lines

S00005 - Odoo

### CODE REVIEW

**Comment by rousseldenis** [comment]
@jdidderen-be Thanks for this. Could you add lines with display_type in action_confirm test in order to avoid regression ?

**Comment by ghost** [comment]
@rousseldenis Should be good now

**Review by rousseldenis — APPROVED** [review]
Code review.

@jdidderen-be

**Review by ikapasi-initos — APPROVED** [review]
Code review and functional
LGTM

**Pull request merged**
