### PR TITLE
[12.0] [FIX] product_contract -> Expected singleton: sale.order(…, …)

### PR DESCRIPTION
**Pull request by khaeusler**
Hello,

we received a singleton error with the method _compute_is_contract.
Could it be that the code in the _compute_is_contract ("product_contract") method is wrong?

### CODE REVIEW

**Review by bodedra — APPROVED** [review]
LG :+1:

**Review by carlosdauden — APPROVED** [review]

**Review by marylla — APPROVED** [review]
Looks good to me. :+1:

**Comment by olaf-wagner** [comment]
Can we merge this please or is anything missing? It will fix a problem for one of our customers. Thanks in advance!

**Comment by marylla** [comment]
@pedrobaeza Hi Pedro, can we merge this please? :)

**Pull request merged**
