### PR TITLE
[IMP] contract: Add computed dates from/to period invoiced

### PR DESCRIPTION
**Pull request by carlosdauden**
This change improves too contract_variable_quantity filters

@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I don't think this a good change. We already have the information on the context, and this allows other modules like line #109 to work without too much changes. Why are you making this change?

contract_variable_quantity has access to context also, so no need for doing this.

**Comment by carlosdauden** [comment]
This change only abstract this implementation
https://github.com/OCA/contract/pull/140/files#diff-47b79491db78ebebcb372014ce9c7bf3L167
to computed fields.

I don't modify context values, therefore other modules can access to it.

Adding operation with relativedelta is not allowed by safe_eval in contract_variable_quantity.

**Comment by pedrobaeza** [comment]
What you are altering is the method for inserting the markers, forcing to use the computed values from contract. Please check #109, which sets periodicity by line, which is broken with this.

And for what you need to use `relativedelta` in the formula for variable quantity? We already have the needed dates.

**Comment by carlosdauden** [comment]
If we already have the needed dates, we don't need this:
https://github.com/OCA/contract/pull/140/files#diff-47b79491db78ebebcb372014ce9c7bf3L167
but date_from and  date_to are computed there.

I don't see what is the problem in the dirty PR https://github.com/OCA/contract/pull/109 to v10.0

**Comment by carlosdauden** [comment]
@pedrobaeza changes done

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@rafaelbn please review

**Review by rafaelbn — APPROVED** [review]
👍

**Pull request merged**
