### PR TITLE
[MIG] contract_sale_invoicing: Migration to 13.0

### PR DESCRIPTION
**Pull request by dantiller2**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@dantiller2 Thanks for this.

Don't hesitate to make a better readable PR's title like your last commit '[MIG] contract_sale_invoicing: Migration to 13.0'.

It will help reviewers when having the PRs list.

**Review by max3903 — APPROVED** [review]

**Review by leemannd — APPROVED** [review]

**Comment by leemannd** [comment]
Hello @dantiller2 . Thank you for your contribution. The tests are failing. Could you have a look?

**Pull request closed without merging**
