### PR TITLE
[13.0] MIG base_contract

### PR DESCRIPTION
**Pull request by alexis-via**
Superseeds PR https://github.com/OCA/contract/pull/397 (I needed to do a rebase).

### CODE REVIEW

**Comment by sergio-teruel** [comment]
@alexis-via Can you add this commit from v12.0?
https://github.com/OCA/contract/pull/506/commits/b61a0cceee0dc33cec54771ce3c84efc6acc677b

**Comment by alexis-via** [comment]
@sergio-teruel Feel free to supersede this PR (close it and propose another PR with your additional commits). I don't plan to work this agreement stuff anymore.

**Comment by sergio-teruel** [comment]
Ok. thanks!! I was imagining that.
So. I think that this PR must be closed

**Comment by alexis-via** [comment]
Yes, you can close it when your new PR is ready (please leave a link to the new PR in the comment).

**Pull request closed without merging**
