### PR TITLE
[FIX] Contracts Management - Recurring: wrong value for account

### LINKED ISSUE #59: [v10] Contracts Management - Recurring: wrong value for account ID
After installation of "Contracts Management - Recurring" module, I create contract for demo customer agrolait, and when I try to create and save invoice for the contract, odoo say
" File "C:\Program Files (x86)\Odoo 10.0\server\odoo\fields.py", line 2011, in convert_to_cache
ValueError: Wrong value for account.invoice.analytic_account_ids: 7"
Same error found in runbot of odoo community.
contr

### PR DESCRIPTION
**Pull request by primes2h**
- Added missing brackets to fix #59 

Thanks @carlosdauden

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you please sign the CLA?

**Comment by primes2h** [comment]
I did it some days ago.

**Comment by pedrobaeza** [comment]
Please include license key in the manifest as it's missing and Travis is complaining about that.

**Review by lasley — APPROVED** [review]
Aside from the missing license key in manifest to clear a pre-existing error.

**Comment by primes2h** [comment]
I've added license in the manifest file. Why is it failing now?

I'm quite new in all this, thanks for understanding. :-)

**Comment by pedrobaeza** [comment]
It doesn't seems to be your fault, Sergio. @lasley it seems website_portal_contract is failing. Can you check?

**Comment by lasley** [comment]
Fixed in #103

**Review by pedrobaeza — APPROVED** [review]
Merging this old one.

**Pull request merged**
