### PR TITLE
[12.0][FIX] - Fix contract migration

### LINKED ISSUE #420: [12.0] contract structural changes migration scripts issue
when I try to upgrade contract module in v12 from 12.0.1.x to 12.0.2.4 which have structural changes in the contract object I get this error:

> Traceback (most recent call last):
  File "/NVME/odoo/ov12/odoo/odoo/odoo/service/server.py", line 1127, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/NVME/odoo/ov12/odoo/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/NVME/odoo/ov12/odoo/odoo/odoo/modules/loading.py", line 417, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/NVME/odoo/ov12/odoo/odoo/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/NVME/odoo/ov12/odoo/odoo/odoo/modules/loading.py", line 195, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/NVME/odoo/ov12/odoo/odoo/odoo/modules/registry.py", line 304, in init_models
    func()
  File "/NVME/odoo/ov12/odoo/odoo/odoo/fields.py", line 2129, in update_db_foreign_key
    new = process(model._cr, model._table, self.name, comodel._table, 'id', self.ondelete or 'set null')
  File "/NVME/odoo/ov12/odoo/odoo/odoo/tools/sql.py", line 185, in fix_foreign_key
    return add_foreign_key(cr, tablename1, columnname1, tablename2, columnname2, ondelete)
  File "/NVME/odoo/ov12/odoo/odoo/odoo/tools/sql.py", line 158, in add_foreign_key
    cr.execute(query.format(tablename1, columnname1, tablename2, columnname2, ondelete))
  File "/NVME/odoo/ov12/odoo/odoo/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/NVME/odoo/ov12/odoo/odoo/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.ForeignKeyViolation: insert or update on table "account_invoice" violates foreign key constraint "account_invoice_old_contract_id_fkey"
DETAIL:  Key (old_contract_id)=(181) is not present in table "contract_contract".

BTW, id 181 is there in the account_analytic_account table which is the old contract model.

help is more than appreciated.

### PR DESCRIPTION
**Pull request by sbejaoui**
Fixes: #420 

This fix the case of migrating contracts without contract lines

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I don't think this is correct. Maybe you can filter on previous distinct + those with recurring_invoices marked.

**Comment by mohamedhagag** [comment]
it still does not fix the issues

I have to work with the DB manually to handle many issues

**Comment by mohamedhagag** [comment]
@sbejaoui @pedrobaeza 

if you want I can share a dump from the DB with anonymized data so you can test the migration scripts

**Comment by pedrobaeza** [comment]
For me this is out of scope of the support, as there should be something that is not in standard modules that provokes the problem.

**Comment by mohamedhagag** [comment]
@pedrobaeza 

I'm not sure what do you mean by standard modules, Odoo modules or OCA modules or both ?

I'm sure that if I uninstalled all 3rd party modules and kept only odoo and oca modules this will not solve the issue.

And I will do so and share the results with you.

Regards,

**Pull request closed without merging**
