### PR TITLE
[16.0][MIG] contract_invoice_start_end _dates: Migration to 16.0

### PR DESCRIPTION
**Pull request by JesusValdez96**
Migration to 16.0 according to migration guide.

### CODE REVIEW

**Comment by JesusValdez96** [comment]
@pedrobaeza could you review this please?

**Comment by pedrobaeza** [comment]
Not using it, sorry.

**Comment by JesusValdez96** [comment]
@moylop260 could you review this?

**Review by rvalyi — APPROVED** [review]
LGTM

**Review by rousseldenis — APPROVED** [review]
Code review

**Pull request merged**
