### PR TITLE
[15.0][FWD] contract : PR #741 #789 #790 from 14.0 to 15.0

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@rousseldenis please, cherry-pick https://github.com/OCA/contract/commit/00eca3a991fa4dabf3cc319f0e5d3b9f13414ac0 and https://github.com/OCA/contract/commit/461afccdb64fd263e4ed96027519f15b25feac34.

**Comment by rousseldenis** [comment]
@MiquelRForgeFlow Done

**Comment by rousseldenis** [comment]
And rebased

**Comment by rousseldenis** [comment]
@OCA/core-maintainers @pedrobaeza @sbidoul 

It seems that Odoo 15 let some errors pass during tests, so pipelines are green but shouldn't.

Are you aware of this ?

See test run here  (Look into 'Run tests'):

https://github.com/OCA/contract/runs/7000226703?check_suite_focus=true

**Review by ntsirintanis — APPROVED** [review]
Code review. Thank you very very much @rousseldenis

**Comment by sbidoul** [comment]
@rousseldenis I reported that upstream a while ago https://github.com/odoo/odoo/issues/80198

**Comment by rousseldenis** [comment]
> @rousseldenis I reported that upstream a while ago [odoo/odoo#80198](https://github.com/odoo/odoo/issues/80198)

Mmmh, yes, I think this is a particular case as we are in a test file but it fails on import.

**Comment by pedrobaeza** [comment]
Should this PR be fixed then or can I merge?

**Comment by rousseldenis** [comment]
> Should this PR be fixed then or can I merge?

I will rebase after #849

**Comment by rousseldenis** [comment]
@pedrobaeza This is ready

**Pull request merged**
