### PR TITLE
[14.0][mig]contract_mandate

### PR DESCRIPTION
**Pull request by hkapatel-initos**
Migration to 14.0
Depends on:

[14.0][MIG] Migarted contract_payment_mode module. #662

### CODE REVIEW

**Review by fshah-initos — APPROVED** [review]
Done code review and Functional test -  LGTM.

**Comment by hkapatel-initos** [comment]
@liweijie0812 and @alvarorib  can you please review this PR?

**Comment by hkapatel-initos** [comment]
@atchuthan can u please review this PR?

**Comment by hkapatel-initos** [comment]
@ygol Goldberg, can you please review this pr?

**Comment by hkapatel-initos** [comment]
it would be nice if someone review here

**Review by sbejaoui — APPROVED** [review]
Code review.

**Review by atchuthan — APPROVED** [review]

**Pull request merged**
