### PR TITLE
[ADD] Invoiced quantity on contract/analytic form, contract line trac…

### PR DESCRIPTION
**Pull request by sysadminmatmoz**
…es to invoice line
Needed to have the planned/invoiced view on the contract form. Contract Line ID traces Invoice Line ID.

### CODE REVIEW

**Comment by sysadminmatmoz** [comment]
If you like the idea, I'll prepare a commit for v12 too.

**Comment by sysadminmatmoz** [comment]
slika

To better illustrate.

**Comment by rafaelbn** [comment]
Hi @sysadminmatmoz , I don't get the idea, in my mind Invoiced qty is equal to plan qty. as in the contract the quantities is what will be invoiced :thinking: 

About v12 we should first merge this PR: https://github.com/OCA/contract/pull/207

**Comment by sysadminmatmoz** [comment]
Plan quantity is what is going to be invoiced. Invoiced qty is what was already invoiced until now.

**Comment by rafaelbn** [comment]
This should be reviewed by contributors



After hundreds of hours reviewing and testing from v8 in this module I'm not a contributor. Sorry I cannot help.

**Pull request closed without merging**
