### PR TITLE
[FIX] looping contract in recurring_create_invoice to support multi r…

### PR DESCRIPTION
**Pull request by pdyharshad**
1. Looping contracts to avoid singleton assertion. 
2. adding a check if recurring_next_date is present before creating a invoice.

### CODE REVIEW

**Review by flotho — APPROVED** [review]
This one seems to superseed #505 

and it looks GTM, 

Thansk a lot

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@pdyharshad please rebase your branch over current 12.0 branch and fix the test, as there's an error when merging in a rebased branch.

**Review by flotho — APPROVED** [review]
LGTM

**Review by marcelsavegnago — APPROVED** [review]

**Comment by sbidoul** [comment]
@pdyharshad 

> adding a check if recurring_next_date is present before creating a invoice.

Why is this new check necessary?

**Comment by pdyharshad** [comment]
> @pdyharshad
> 
> > adding a check if recurring_next_date is present before creating a invoice.
> 
> Why is this new check necessary?

I got an error when the recurring_next_date was not set on the contract, as it is used in searching sales order ahead.

**Comment by pdyharshad** [comment]
> @pdyharshad please rebase your branch over current 12.0 branch and fix the test, as there's an error when merging in a rebased branch.

@pedrobaeza Done. Can you please merge again.

**Pull request merged**
