### PR TITLE
[12.0][IMP] contract: Allow to set a manual currency

### PR DESCRIPTION
**Pull request by pedrobaeza**
Done through an extra field + inverse in the existing compute. This way, we have the flexibility of auto-remove custom value if it matches the computed one + we don't need extra changes in the rest of the code.

cc @Tecnativa TT24071

### CODE REVIEW

**Review by carlosdauden — APPROVED** [review]
I think simply assigning `inverse=lambda self: self` would avoid all this code, but since I know you don't like it and that in v13 that same inverse is achieved with `readonly=False`, which is to your liking, I have no problem approving this PR. :wink:

**Comment by pedrobaeza** [comment]
Well, I thought about that, but the problem using `lambda` (or the equivalent whole method), is that the manual currency is assigned as soon as you save the first time, so the compute remains only as a "default value". That's why I have put full inverse method with the check for a different value.

**Review by rafaelbn — APPROVED** [review]
:+1:

**Pull request merged**
