### PR TITLE
[16.0][MIG] contract_sale

### PR DESCRIPTION
**Pull request by CRogos**
Migration using oca-port tool
replacing #915
- git history according to style guide
- replaced account_analytic_tag_contract_salesman by model_account_analytic_plan_contract_salesman instead of deleting

### CODE REVIEW

**Comment by JesusValdez96** [comment]
@CRogos reduce commits from OCA bots: https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate

And check the migration guide: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

**Comment by CRogos** [comment]
@JesusValdez96 could give a short comment if this is the right way or what could be improved (next time)?
image

**Comment by JesusValdez96** [comment]
@CRogos change to fixup all commits of oca-transbot, oca-travis, oca-git-bot and oca-ci and pick commit f70ad158 of sbejaoui

**Comment by JesusValdez96** [comment]
@CRogos LGTM could you announce this PR in [Migration to version 16.0](https://github.com/OCA/contract/issues/880)?

**Comment by MohamedOsman7** [comment]
LGTM

**Review by MohamedOsman7 — APPROVED** [review]

**Review by MohamedOsman7 — APPROVED** [review]

**Comment by CRogos** [comment]
@JesusValdez96 would you add a review approval?

**Review by JesusValdez96 — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
