### PR TITLE
[13.0][IMP] contract : Update res_partner_view.xml

### PR DESCRIPTION
**Pull request by Martronic-SA**
No need to write on customer_rank and supplier_rank here. This creates a conflict with partner_manual_rank module.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
If they are invisible, there can't be any write on them. Or am I missing something?

**Comment by rousseldenis** [comment]
@Martronic-SA Could you improve your commit message like `[IMP] contract: (...)` and fix pre-commit ? Thanks

**Comment by rousseldenis** [comment]
> If they are invisible, there can't be any write on them. Or am I missing something?

Mmmmh, not sure they are not part of write() values.

**Comment by pedrobaeza** [comment]
No as long as they are not modified, which is the case being invisible.

**Comment by Martronic-SA** [comment]
Maybe beacause they are part of partner_manual_rank fields dependence?
The problem appears only when both modules are installed.
You set "Is Customer" on new contact, save, then modify the contact (modify the name), save, and the "Is Customer" check has gone. I fixed this by setting readonly on customer_rank and supplier_rank in contract form view.

**Comment by pedrobaeza** [comment]
That sounds very weird to me... but it seems something to be fixed on `partner_manual_rank` instead of here. And please don't ignore the comments about the commit message format and don't add several commits.

https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message

**Comment by Martronic-SA** [comment]
Ok it's happening only when adding a contact to the main partner.
Somehow the contact sets back it's customer_rank = 0 to the parent and as long as customer_rank is added as "writable" field in the form by contract module, it then writes the new customer_rank on save.
So this PR is not really relevant here.

**Comment by Martronic-SA** [comment]
I close the PR. Needs further investigations.

**Pull request closed without merging**
