### PR TITLE
[FIX] contract_sale_generation: Isolate sale generation

### LINKED ISSUE #117: [BUG] 10.0 contract_sale_generation: Mixing apples and oranges: account.invoice().union(sale.order(11,))
Running the command:
`~/odoo-10.0/odoo-bin -d moy6 --db-filter=^moy6$ --stop-after-init --log-level info --log-handler openerp.tools.yaml_import:DEBUG --test-enable --init agreement_account,agreement_sale,contract,contract_payment_auto,contract_payment_mode,contract_sale,contract_sale_generation,contract_show_invoice,contract_variable_quantity,product_contract,website_portal_contract`

Using the fix https://github.com/OCA/contract/pull/116

```log
2017-11-10 05:52:24,660 6397 ERROR openerp_test odoo.addons.contract_sale_generation.tests.test_contract_sale: ERROR: test_contract (odoo.addons.contract_sale_generation.tests.test_
contract_sale.TestContractSale)
2017-11-10 05:52:24,662 6397 ERROR openerp_test odoo.addons.contract_sale_generation.tests.test_contract_sale: Traceback (most recent call last):
2017-11-10 05:52:24,662 6397 ERROR openerp_test odoo.addons.contract_sale_generation.tests.test_contract_sale: `   File "contract_sale_generation/tes
ts/test_contract_sale.py", line 66, in test_contract
2017-11-10 05:52:24,663 6397 ERROR openerp_test odoo.addons.contract_sale_generation.tests.test_contract_sale: `     self.contract.recurring_create_invoice()
2017-11-10 05:52:24,663 6397 ERROR openerp_test odoo.addons.contract_sale_generation.tests.test_contract_sale: `   File "contract/models/account_anal
ytic_account.py", line 231, in recurring_create_invoice
2017-11-10 05:52:24,663 6397 ERROR openerp_test odoo.addons.contract_sale_generation.tests.test_contract_sale: `     invoices |= contract.with_context(ctx)._create_invoice()
2017-11-10 05:52:24,664 6397 ERROR openerp_test odoo.addons.contract_sale_generation.tests.test_contract_sale: `   File "odoo-10.0/odoo/models.py", line 5128, in __or__
2017-11-10 05:52:24,664 6397 ERROR openerp_test odoo.addons.contract_sale_generation.tests.test_contract_sale: `     return self.union(other)
2017-11-10 05:52:24,665 6397 ERROR openerp_test odoo.addons.contract_sale_generation.tests.test_contract_sale: `   File "odoo-10.0/odoo/models.py", line 5137, in union
2017-11-10 05:52:24,665 6397 ERROR openerp_test odoo.addons.contract_sale_generation.tests.test_contract_sale: `     raise TypeError("Mixing apples and oranges: %s.union(%s)" % (sel
f, arg))
2017-11-10 05:52:24,665 6397 ERROR openerp_test odoo.addons.contract_sale_generation.tests.test_contract_sale: TypeError: Mixing apples and oranges: account.invoice().union(sale.order(11,))
```

Build log https://travis-ci.org/OCA/contract/jobs/300014336#L1430

### PR DESCRIPTION
**Pull request by angelmoya**
Closes #117

### CODE REVIEW

**Comment by angelmoya** [comment]
@pedrobaeza @moylop260 could you check this, please

**Review by pedrobaeza — APPROVED** [review]
Please change module version number, but I see it OK.

**Comment by pedrobaeza** [comment]
@moylop260 please review

**Review by moylop260 — APPROVED** [review]
just use a better title using the name of the module changed

**Review by carlosdauden — APPROVED** [review]

**Pull request merged**
