### PR TITLE
[9.0][IMP] Add type to analytic account / contract

### PR DESCRIPTION
**Pull request by funbaker**
Prerequisite for https://github.com/OCA/contract/pull/96

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Is this going to be continued?

**Comment by funbaker** [comment]
Yes, but i got one question about this.

Tests are failing because of ``ERROR openerp_test openerp.addons.contract_recurring_analytic_distribution.tests.test_contract_recurring_distribution: ` ValueError: Wrong value for account.analytic.account.type: 'contract'`` caused by https://github.com/OCA/contract/blob/9.0/contract_recurring_analytic_distribution/tests/test_contract_recurring_distribution.py#L24-L36 but i cannot find the place where ``account_analytic_account.type`` is defined.

Do you have an idea?

**Comment by pedrobaeza** [comment]
You shouldn't use the word `type`, as it's a reserved word in Python. Use `contract_type`.

**Comment by funbaker** [comment]
Will do, but isn't it used in odoo/odoo a lot?

**Comment by pedrobaeza** [comment]
Yes, indeed, but it can cause several glitches. I don't know if the Travis problem is caused here by that or by anything else.

**Comment by pedrobaeza** [comment]
@funbaker you can see that this has been adopted for v11 for generating purchases and finally without a new module. Are you interested in finishing this for v9 or should we close it?

**Comment by funbaker** [comment]
In this case i'll rather backport it to v10 in a new PR.

**Pull request closed without merging**
