### PR TITLE
[FIX] contract: change where security is given to group_account_invoi…

### PR DESCRIPTION
**Pull request by albariera**
…ce: from contract_sale to contract

Cherry pick from #721

### CODE REVIEW

**Review by etobella — APPROVED** [review]

**Review by flotho — CHANGES_REQUESTED** [review]
Hi,
thanks for this tip https://github.com/OCA/contract/pull/722/files#diff-5224549c457c0823a535d61c04d101c428c8c4e6e0fd49139971fe293b6ebc78R45
As it's not possible to display such info in Odoo UI could you please :

- Maybe add this record with a noupdate attribute will prevent bad later computation
- Change a bit the rule name to reflect the info in the source code

**Comment by albariera** [comment]
@flotho Sorry for the delay. I hope the name is better now, if you have any other proposals let me know. 
The noupdate attribute is already present in the odoo tag.

**Review by flotho — APPROVED** [review]

**Comment by flotho** [comment]
@albariera I think you also need a rebase

**Comment by etobella** [comment]
Already merged by https://github.com/OCA/contract/pull/789

**Pull request closed without merging**
