### PR TITLE
[10.0] [ADD] contract_auto: Automatic Payment For Contracts

### PR DESCRIPTION
**Pull request by lasley**
Contract Auto (RFC #55)
=============

This module allows for the configuration of automatic payments on invoices that are created by a contract.

Usage
=====

Enable Automatic Payment
------------------------

* Navigate to a customer contract
* Check the `Auto Pay?` box to enable automatic payment
* Configure the options as desired
* Set the `Payment Token` to the payment token that should be used for automatic payment

Automatic Payment Settings
--------------------------

The following settings are available at both the contract and contract template level:

| Name | Description |
|------|-------------|
| Invoice Message | Message template that is used to send invoices to customers upon creation. |
| Payment Retry Message | Message template that is used to alert a customer that their automatic payment failed for some reason and will be retried. |
| Payment Fail Message | Message template that is used to alert a customer that their automatic payment failed and will no longer be retried. |
| Auto Pay Retries | Amount of times to attempt an automatic payment before discontinuing and removing the payment token from the contract/account payment method. |
| Auto Pay Retry Hours | Amount of hours that should lapse until retrying failed payments. |

Payment Token
-------------

A valid payment token is required to use this module. These tokens are typically created during the `website_sale` checkout process, but they can also be created manually at the acquirer.

A payment token can be defined in one of two areas:

* Contract - Defining a payment token in the contract will allow for the use of this token for automatic payments on this contract only.
* Partner - Defining a payment token in the partner will allow for the use of this token for automatic payments on all contracts for this partner that do not have a payment token defined.

### CODE REVIEW

**Comment by vonpupp** [comment]
Thank you @lasley. Yesterday I had some problems during installation (XML issues) but now I could install it fine. I just created a contract and I will have to wait to see if everything goes fine. I wonder a couple of things:
(1) Wouldn't be interesting to define a payment-gateway to be used on a contract?
(2) How do I define a credit card number for the person who is the contract owner?

What if the customer decides to switch to another payment method which involves switching to another payment-gateway? (this scenario is related to my first question).

I would like to test the module using stripe, which implements s2s methods, however I don't understand how a specific person will be charged for a contract. Do you know how to debug this to try to understand better the process? What first comes to my mind is to save the customer on the stripe backend and link a credit card number as primary so it can be automatically retrieved during the payment, but I will have to test that.

**Comment by lasley** [comment]
The payment token represents the credit card, which is linked to a partner and acquirer. Changing either is as easy as changing the payment token. 

The catch here is that the credit card already has to be saved to the partner's account as a payment token. This happens during the website_sale checkout process if the customer checks the option to remember their card. You can also create a token at your acquirer manually and add into Odoo for use.

**Comment by rafaelbn** [comment]
Hi @lasley ,

Please could you add a usage section detailed in order to know what to test?

After seeing this PR I have read again https://github.com/OCA/contract/issues/55 and https://github.com/OCA/contract/issues/45#issuecomment-286616680 but I have some doubts about how it works.

You want that contract set invoices paid base on? I read "This module adds logic to automatically pay invoices that are created by a contract" but I don't understand why you want invoices paid without knowing if they are paid o not really with a transfer, bank card, paypal or similar.

I'm interested.

Thanks

**Comment by lasley** [comment]
@rafaelbn - readme updated & instructions added to the main comment of this PR. Let me know if this doesn't clarify.

**Comment by vonpupp** [comment]
@lasley, thank you very much for your guidance; It makes total sense now! Stripe is missing this important feature (saving the credit card). I am trying the module using authorize, however even though I check the "remember the CC details", it doesn't seem to be remembered at all. Truth to be told I am still struggling with authorize itself (the payment gets processed properly but the return URL doesn't seem to work, I need to further dig into this). I assume that the payment.token is created prior redirecting to authorize.net website and the failed return to the odoo website has nothing to do with it (not 100% sure though).

I tried to create a payment token manually by going (with developer mode) to Accounting / Configuration / Payments / Saved Payment Data, however I am not sure how to fill the acquirer Ref. I guess it is the token which maps to the record with the payment-gateway website record (some sort of id).

Unfortunately I am having some troubles to test this out, since as for today, the only two acquirers that I am aware that support remembering the payment details are authorize and ogone. Ogone is a nightmare to setup (I need more time) and authorize doesn't seem to remember anything.

If I achieve something with authorize I will be more than happy to document it along with the readme (or in a separated folder)

**Comment by lasley** [comment]
@vonpupp - the payment token memorization definitely works with a proper Authorize setup, so I would assume it's just something in the configuration. Make sure that you're using a sandbox account set to live mode in the Authorize console, and that you set the acquirer to sandbox mode in Odoo.

Regarding Stripe, I see all of the server to server methods implemented in the v10 acquirer, such as the [token creation](https://github.com/odoo/odoo/blob/10.0/addons/payment_stripe/models/payment.py#L174)

**Comment by vonpupp** [comment]
Thank you very much @lasley. Yes indeed the problem is on my side. Apparently the payment information gets saved once it succeeds. Authorize.net does not seem to be documented. I have found [this issue], which pretty much describes my problem. I have configured the URLs accordingly however the problem persists (Default Receipt URL is <URL>/shop/confirmation and Default Relay Response URL is <URL>/payment/authorize/return).

I configured also the silent URL to be a [request bin], to check out the POST parameters coming back from authorize.net so I try to replicate the request using curl. The sad part is that I always get a 404 on odoo when trying to access route `/payment/authorize/return/`, I don't know why though so I need to investigate the issue further.

Sorry that I haven't been helpful in testing your module. Hopefully I will manage to solve all this issues soon. Unfortunately Stripe do not allow to remember the payment details.

[this issue]: https://github.com/odoo/odoo/issues/14007
[request bin]: http://requestb.in/137j5x21?inspect

**Comment by lasley** [comment]
> Unfortunately Stripe do not allow to remember the payment details.

It does though, I linked the token creation above. I definitely see it taking credit card numbers, then turning it into a payment token. Maybe try skipping the process entirely & just use [`stripe_create` directly](https://github.com/odoo/odoo/blob/10.0/addons/payment_stripe/models/payment.py#L174)

**Comment by lasley** [comment]
This is ready for review if a PSC would please mark as such. I just need to fix a few missing test holes, but no functional code

**Comment by vonpupp** [comment]
@lasley thank you for your patience! I finally could make authorize to work. I had to destroy the server and recreate it again, something very very weird was going on with the controller routes and 404 error responses (I think I messed up some python dep).

I have tested stripe with the regular process and I noticed that the "remember" check is on a different place. It resides on the stripe.js form shown to the user and when checked it asks for the phone number. On future purchases, the phone number is used to receive a code which authenticates that user within Stripe and allows the user to push the `pay now` button.

I am manually creating a payment.token however I am not sure what to use on the acquirer ref field. I guess is the customer id which I can get from the Stripe interface `cus_xxx`. Could you please clarify this? I couldn't understand properly, sorry. On every credit card charge on the autopay feature from contracts, doesn't Stripe send you an SMS with a code?

Thank you very much once again for your patience and help. I am learning a lot. Hopefully I will be able to implement this at the NGO I am a volunteering for.

**Comment by lasley** [comment]
TBH I'm not sure how Stripe works, but I think you're confusing Stripe's automatic payment service with that of what I am doing here. We are not utilizing the automatic payment functionality of any of the acquirers, but are instead using the saved payment tokens to charge cards that are already known.

**Comment by vonpupp** [comment]
I don't think so but now that authorize.net works, I can finally test the module, understand it better and compare it properly with stripe =)

I was thinking of other use cases, i.e: send payment email notification with a `pay now` button (useful for Paypal), or attaching a banking slip (money order, "boleto" in portuguese, not sure about the translation). I will try to add these features when I am more odoo-fluent.

**Comment by vonpupp** [comment]
@lasley, Excuse me to annoy you again. I would like to please confirm something.

I have noticed that the invoices even when paid, they still remain as open state.
2017-05-12-212009_2720x1024_scrot

Here is a screenshot of the payment confirmations.
2017-05-12-211954_2720x1024_scrot

Should the invoice status be changed to paid/done automatically, or this is the expected behavior and then some sort of conciliation process should take care of those status change? Thank you very much.

**Comment by lasley** [comment]
@vonpupp - I don't think any of that is controlled by my module. There are acquirer settings that would dictate what happens with the invoice after payment.

**Comment by vonpupp** [comment]
Thank you @lasley. I guess you are referring to the option: "Authorize & capture the amount, confirm the SO and auto-validate the invoice on acquirer confirmation". This work ok when using the regular ecommerce flow (which creates a S.O), but does not seem to validate the invoice when used in contracts (maybe because no S.O is created). Just for your information.

I am personally very happy with the module and I want to thank you very much for your efforts. I will try to dig into the Stripe and "remember the credit card" issue.

Thank you once again and big kudos!

**Comment by lasley** [comment]
@vonpupp - Ah yup you're right about that. So we'd need some sort of option in the acquirer added to perform similar functionality. That's a good module idea - you should make an RFC for it (and/or write it if you have time).

Sweet so this module works? If so, can you please add an approval in the "Files Changed" tab & just note that it was from a functional standpoint only (unless you also reviewed the code).

**Review by vonpupp — APPROVED** [review]
LGTM

**Comment by vonpupp** [comment]
@lasley. I approved as requested.

Regarding the option in the acquirer to automatically change the status, do you think it would be usable by all the acquirers or is something that needs to be done per-acquirer basis? Could you point me into a sane starting point, please?

Perhaps writing a subscription module that would create a new S.O. instead of an invoice, so the Odoo workflow can be followed normally would be interesting. This might be easier to maintain in the future (speculations though). Any thoughts? With my little Odoo knowledge, writing this subscription module will take me quite a long time and I would rather first put into production the Odoo I am preparing for the NGO first so that I can later focus on this (they need it quite urgently). But it something I would like to try in the future.

**Comment by lasley** [comment]
> Could you point me into a sane starting point, please?

Totally. First, I think you should make an RFC [like this one](https://github.com/OCA/contract/issues/65) so we can move the conversation into an appropriate context.

Second, take a look at how it happens in [website_portal_sale](https://github.com/odoo/odoo/blob/5bd8f97fa2fd572614f321a747b3cac140bb8a1d/addons/website_portal_sale/models/payment.py#L61). It'll definitely work for all acquirers, we're just modifying invoice statuses. Our implementation will be much simpler.

> Perhaps writing a subscription module that would create a new S.O. instead of an invoice, so the Odoo workflow can be followed normally would be interesting. 

Generating a sale per contract invoicing would not be ideal. A sale is a representation of an agreement to purchase something - in the context of a contract, that's the agreement to purchase the recurring billing. Invoices are related specifically to requesting and subsequently receiving payment from customers.

**Comment by vonpupp** [comment]
Amazing, @lasley. Thank you very much!

I created #70 for this purpose. Please feel free to give your impressions. Just to be clear, you provided the `website_portal_sale` as an example, but I don't need to modify nothing there, right?

Currently I am working on the missing parts of the `payment_stripe` module, it seems to miss some parts to properly work with s2s. Afterwards I will dig into #70 by my own to try to contribute :). Then I would like to have a look at the #45 which seems to be the natural progression of your work here.

**Comment by rafaelbn** [comment]
Hi, could I propose `contract_payment_auto` ? contract_auto is ambiguous IMHO. 

Testing I get and error when filling Payment token in the partner check, Do you know why?:

**Comment by lasley** [comment]
@rafaelbn - I agree with the rename.

Looks like I forgot to add `payment_token_ids` to the partner view. Should be good now!

**Comment by rafaelbn** [comment]
Hi @lasley travis is red, could you take a look please?

**Comment by lasley** [comment]
Alright we're 🍏 !

**Comment by lasley** [comment]
Any PSC have thoughts on this one?

**Comment by rafaelbn** [comment]
Hi @lasley I'm rebuilding for testing but it looks runbot is broken everywhere... 😞

**Comment by lasley** [comment]
@rafaelbn - I rebuilt and it looks good now. must have been the space issue from earlier

**Review by rafaelbn — APPROVED** [review]
Tested 👍 

@lasley do you want to squash before merge?

**Pull request merged**
