### PR TITLE
[14.0] [IMP] subscription_oca: modify tree view

### PR DESCRIPTION
**Pull request by renda-dev**
- Add start date
- Add finish date
- Change 'Etapa' string to 'Stage'

### CODE REVIEW

**Review by HekkiMelody — APPROVED** [review]
Code review

**Review by francesco-ooops — APPROVED** [review]
LGTM

**Comment by francesco-ooops** [comment]
@OCA/logistics-maintainers can this be merged?

**Comment by PicchiSeba** [comment]
Code Review: LGTM

**Review by PicchiSeba — APPROVED** [review]

**Pull request merged**
