### PR TITLE
[13.0][MIG] contract_price_revision + improvements

### PR DESCRIPTION
**Pull request by rousseldenis**
- [x] Added a fixed price revision
- [x] Improved the manner new line values are retrieved
- [x] Added a field to restrict revision on some lines.

### CODE REVIEW

**Comment by rousseldenis** [comment]
@cubells @pedrobaeza This is the continuation of #627 

@pedrobaeza Your last comment is attended

**Review by pedrobaeza — APPROVED** [review]

**Review by rafaelbn — APPROVED** [review]
👍

**Pull request merged**
