### PR TITLE
ADD 8.0 contract account banking mandate v2

### PR DESCRIPTION
**Pull request by elacunza**
Follow up to #37, incorrectly asked to merge to 9.0 branch. This module is for 8.0 branch as it is now.

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by dreispt** [comment]
This just adds the field.
I was expecting to see also some logic to associate the mandate with the invoice's payment form.
At least the invoice report should also be changed to include that mandate information.

**Comment by elacunza** [comment]
@dreispt This adds the field and fills in the field in the recurring invoice when it is generated.
The invoice report should be changed in account_banking_mandate, because that is the module that adds the mandate field to invoices.

**Comment by dreispt** [comment]
OK :+1:

**Review by susport — APPROVED** [review]
👍

**Review by carlosdauden — APPROVED** [review]

**Comment by carlosdauden** [comment]
:+1:

**Pull request merged**
