### PR TITLE
[12.0][FIX] - duplicate payement mode in supplier form views

### PR DESCRIPTION
**Pull request by flotho**
allow to prevent duplicate fields on supplier views

### CODE REVIEW

**Review by sbejaoui — APPROVED** [review]
LGTM, thank you

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Don't replace, but change `domain` attribute if that's the problem.

**Comment by flotho** [comment]
@pedrobaeza the point is that this field is also called in another view. So it's really a duplicate issue in the field view get and not a domain issue.
That's why I used replaced

**Comment by sbejaoui** [comment]
@flotho ,

@pedrobaeza point is to avoid losing other attributes from the base view. 

It's not the case today, but it make sense in a scalability logic if one day we add `attrs` or change the label with `string`.

Changing the domain will resolve the duplicate issue

**Comment by flotho** [comment]
@pedrobaeza @sbejaoui ,

Thanks I read too fast and too late. I change this

**Comment by pedrobaeza** [comment]
Travis is red. I think you have to encode the quotes. Please also squash in one commit.

**Comment by flotho** [comment]
Hi @pedrobaeza ,

Travsi is Green and runbot failed.
i didin't succeed in getting the logs to see if I can do something from my side, sorry for this newbie question

**Comment by pedrobaeza** [comment]
Runbot error:
```

Field 'domain' used in attributes must be present in view but is missing:
 - 'domain' in attrs="{'invisible': [('domain', '!=', 'purchase')]}"
 - 'domain' in attrs="{'invisible': [('domain', '!=', 'sale')]}"

Error context:
View `invoice.button.agreement.form`
[view_id: 1086, xml_id: n/a, model: agreement, parent_id: 334]
None" while parsing /home/odoo/dependencies/contract/agreement_account/views/agreement.xml:36, near
<record id="agreement_form" model="ir.ui.view">
        <field name="name">invoice.button.agreement.form</field>
        <field name="model">agreement</field>
        <field name="inherit_id" ref="agreement.agreement_form"/>
        <field name="arch" type="xml">
            <div name="button_box" position="inside">
                <button class="oe_stat_button" type="action" name="%(account.action_invoice_refund_out_tree)d" context="{'search_default_agreement_id': active_id, 'default_agreement_id': active_id, 'default_partner_id': partner_id}" attrs="{'invisible': [('domain', '!=', 'sale')]}" icon="fa-pencil-square-o">
                        <field string="Customer Invoices" name="out_invoice_count" widget="statinfo"/>
                </button>
                <button class="oe_stat_button" type="action" name="%(account_invoice_in_invoice_refund_action)d" context="{'search_default_agreement_id': active_id, 'default_agreement_id': active_id, 'default_partner_id': partner_id}" attrs="{'invisible': [('domain', '!=', 'purchase')]}" icon="fa-pencil-square-o">
                        <field string="Vendor Bills" name="in_invoice_count" widget="statinfo"/>
                </button>

            </div>
        </field>
    </record>
```

**Review by marylla — APPROVED** [review]
Thanks for solving this. I was very confused about the duplicated field with the wrong domain.
I would have done this with the attribute node as well, so looks good to me. :+1: 
And it also works checking the runbot.

@pedrobaeza Could you re-review, because I think it is correct now.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
