### PR TITLE
[12.0][IMP] contract: Add link to contract line in contract chatter messages

### PR DESCRIPTION
**Pull request by qgroulard**
On contracts, it might be difficult to know which contract line chatter messages refer to.
Thus, this PR adds a link to the contract line form view in the messages.

### CODE REVIEW

**Review by sbejaoui — APPROVED** [review]
LGTM, thanks

**Review by gva-acsone — APPROVED** [review]
LGTM Functional test

**Review by marcelsavegnago — APPROVED** [review]

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Please adapt all of the existing translations, or the fuzzy match will break all languages, not having the number of needed placeholders.

And this is `[IMP]`, not `[ADD]`, as this is not a new module.

**Comment by sbidoul** [comment]
> or the fuzzy match will break all languages

@pedrobaeza do you think we should disable fuzzy matching in weblate?

**Comment by pedrobaeza** [comment]
If not 100% match, I think it should be disabled. Anyway, doing this change will force to re-translate that strings, so it's better to make the substitution in .po files, as there's no translatable content added. I would admit a refactoring of the strings for letting outside the placeholders and avoid errors due to this.

But wait...

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
`_(` is applied after placeholder replacing, so this is not going to be translated ever.

**Comment by sbejaoui** [comment]
@qgroulard can you check @pedrobaeza comment,

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by rousseldenis** [comment]
@qgroulard Could you rebase ?

**Comment by rousseldenis** [comment]
@pedrobaeza Could you update your review ?

**Comment by pedrobaeza** [comment]
It still has the same problem. You should apply .format after the call to translate _

**Comment by rousseldenis** [comment]
@qgroulard Indeed. If you let like this, source strings will have different values to be translated...

**Comment by rousseldenis** [comment]
@qgroulard

**Review by rousseldenis — APPROVED** [review]
@pedrobaeza Could you update your comments?

**Comment by pedrobaeza** [comment]
The `for` word doesn't make sense in this context, as now we are referring directly to the line, not to the product.

**Comment by qgroulard** [comment]
> The `for` word doesn't make sense in this context, as now we are referring directly to the line, not to the product.

The href leads to the line but the text displays the product name.

**Comment by rousseldenis** [comment]
> The `for` word doesn't make sense in this context, as now we are referring directly to the line, not to the product.

Product is just the alias for line name. So, it is not really referred to product only.

image

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Yes, it's OK, as the link text is still the product.

**Comment by pedrobaeza** [comment]
The PO files are not correct after this change. Please fix them.

**Comment by qgroulard** [comment]
@pedrobaeza I believe the " not escaped was the cause of the error.
Could you please retry ?

**Pull request merged**
