### PR TITLE
[ADD] website_portal_contract: Added Spanish translations.

### PR DESCRIPTION
**Pull request by Abranes**
Added es.po for Spanish translation.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
There are texts not translated (but not emptied) and other with some words not very appropriated like "Pinche" instead of "Pulse". Please review this.

**Comment by lasley** [comment]
Sorry for my naivety on this - aren't translations submitted, reviewed, and pushed through Transifex?

**Comment by Abranes** [comment]
The "Pinche"/"Pulse" translation was solved (was a problem with auto-suggestion of poedit).
The other not translated texts was because is a demo contract and I think that no one need the translations.

**Comment by pedrobaeza** [comment]
@Abranes you still need to empty the strings if you are not going to translate them.

@lasley there should be a problem with Transifex script right now because there's no strings there, so this is why I'm admitting this.

**Comment by Abranes** [comment]
@pedrobaeza Sorry, I don't understand you the first time, now it's done.

**Review by pedrobaeza — APPROVED** [review]
Fast-tracking as this is translation

**Pull request merged**
