### PR TITLE
[16.0][MIG] contract_price_revision: Migration to 16.0

### PR DESCRIPTION
**Pull request by houzefa-abba**
Fix views in the process; variation % was not showing inside line list embedded into contract forms.

## Test case on runboat

Contract starts in 2024, invoiced every year, first invoice got produced, price = $500:
Screenshot at 2024-01-16 09-52-26

Run wizard with 10% increase in 2025:
Screenshot at 2024-01-16 09-52-49

The wizard stops my initial contract line and adds a new one in 2025 with price = $550:
Screenshot at 2024-01-16 09-53-15

### CODE REVIEW

**Comment by houzefa-abba** [comment]
Hi @carlosdauden @carolinafernandez-tecnativa this PR is ready, please review

**Comment by carolinafernandez-tecnativa** [comment]
Functional Review LGTM :) Could you please squash administrative commits? Thanks!!

**Comment by houzefa-abba** [comment]
> Functional Review LGTM :) Could you please squash administrative commits? Thanks!!

Thanks for the review! :)

I already squashed some bot & translation commits, which ones do you have in mind? Maybe the 13.0 ones? I'm hesitant in squashing those as they add features

**Comment by carolinafernandez-tecnativa** [comment]
image


> > Functional Review LGTM :) Could you please squash administrative commits? Thanks!!
> 
> Thanks for the review! :)
> 
> I already squashed some bot & translation commits, which ones do you have in mind? Maybe the 13.0 ones? I'm hesitant in squashing those as they add features

I attached the ones I was telling you before

image

**Comment by houzefa-abba** [comment]
Done! Looks better indeed

**Comment by carolinafernandez-tecnativa** [comment]
Other thing you need to take into account according to this document https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0 you need to separate pre-commit init from migration 

Also commits about Translations you need to squash them.

**Comment by houzefa-abba** [comment]
> Other thing you need to take into account according to this document https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0 you need to separate pre-commit init from migration
> 
> Also commits about Translations you need to squash them.

Hi pre-commit did not change anything in this case so there was nothing to commit pre-migration - my 16.0 migration commit does not contain any code formatting changes, unless you spot a specific one?

I already squashed translation commits, could you show me which ones remain to be squashed please?

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by houzefa-abba** [comment]
Rebased on latest 16.0

**Review by TelmoSuarez — COMMENTED** [review]
LGTM!

**Review by enriquemartin — COMMENTED** [review]
LGTM!

**Comment by houzefa-abba** [comment]
Thanks for reviews - I just rebased on latest 16.0, no code changes

**Pull request closed without merging**
