### PR TITLE
[14.0][FIX] contract: bug onchange date_start (comparaison between bo…

### PR DESCRIPTION
**Pull request by mourad-ehm**
comparaison between bool and date

### CODE REVIEW

**Comment by mourad-ehm** [comment]
ping @hparfr

**Comment by scigghia** [comment]
@mourad-ehm maybe this pr could solve this issue?
https://github.com/OCA/contract/issues/818

**Comment by mourad-ehm** [comment]
@scigghia Yes. Could you approve this PR ? thanks

**Review by scigghia — APPROVED** [review]
LGTM

**Review by CRogos — APPROVED** [review]

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Please indicate steps to reproduce the problem and a regression tests is advisable. Please also squash commits into one.

**Comment by scigghia** [comment]
> Please indicate steps to reproduce the problem and a regression tests is advisable. Please also squash commits into one.

@pedrobaeza take a look to the issue #818 please
there is a gif showing the error

**Comment by pedrobaeza** [comment]
As this PR contains several commits, I have cherry-picked them and squashed together and push to the branch at 42b1bffef4294ba202d274f6898a1f19c1d32edf to get this solved at all. Thanks for the patience.

**Comment by pedrobaeza** [comment]
Cherry-picked for v15 at eda6d54d63b055046b3044abe40e332511a02978

**Pull request closed without merging**
