### PR TITLE
[14.0][MIG] agreement_legal_sale_fieldservice (Version 12.0 to 14.0)

### PR DESCRIPTION
**Pull request by patrickrwilson**
Depends on:
- agreement_legal_sale #672 
- fieldservice_agreement https://github.com/OCA/field-service/pull/781
- fieldservice_sale https://github.com/OCA/field-service/pull/761

### CODE REVIEW

**Review by dsolanki-initos — CHANGES_REQUESTED** [review]
@patrickrwilson squash all the commits in this [MIG] base_substate: Migration to 14.0

**Comment by dsolanki-initos** [comment]
@patrickrwilson Can you rebase this branch?

**Comment by dsolanki-initos** [comment]
@patrickrwilson Can you make Travis happy?

**Comment by dsolanki-initos** [comment]
@patrickrwilson It would be nice if you can make Travis green

**Comment by dsolanki-initos** [comment]
Hello @patrickrwilson, can you please modify test cases to make travis green?

**Comment by dsolanki-initos** [comment]
@patrickrwilson can we see the travis green?

**Comment by patrickrwilson** [comment]
@dsolanki-initos unless i'm missing something, Travis is fine with this module but unhappy with aggreement_sale. I'm not sure how to fix that in this PR.

**Comment by dsolanki-initos** [comment]
@patrickrwilson as you have write test cases so there is field name "tracking" which is required and you are not adding values for it in the test case. can you please modified and check it for make travis happy.

**Comment by dsolanki-initos** [comment]
@patrickrwilson can we see the travis green?

**Comment by dsolanki-initos** [comment]
@patrickrwilson can you please check failed checks?

**Comment by dsolanki-initos** [comment]
@patrickrwilson can we see travis green?

**Comment by rousseldenis** [comment]
@patrickrwilson Could you fix this ? Thanks

**Comment by dsolanki-initos** [comment]
@patrickrwilson Can you please fix failed checks?

**Comment by patrickrwilson** [comment]
I'm not sure how to fix this, pointers?
image

**Comment by rousseldenis** [comment]
> I'm not sure how to fix this, pointers? image

Have you installed pre-commit before committing ?

**Comment by patrickrwilson** [comment]
I'm fairly certain I did however it's been over a year since I committed this. I will try to take a look at this again but may be a bit till I can, if someone else wants to take this over feel free to do so.

**Comment by dsolanki-initos** [comment]
@patrickrwilson can you please fail check?

**Comment by dsolanki-initos** [comment]
@patrickrwilson You do not need to define "tracking" to "none" by default it is "none" so you can remove it.

**Comment by patrickrwilson** [comment]
@dsolanki-initos I removed the tracking: none in test but isn't it failing on agreement_legal module tests and not this one? I could be reading this wrong.
image

**Pull request closed without merging**
