### PR TITLE
[14.0][MIG] agreement_repair

### PR DESCRIPTION
**Pull request by Vimal-OSI**

### CODE REVIEW

**Review by dsolanki-initos — CHANGES_REQUESTED** [review]
We need to follow the guideline to commit. You can have a look at the below link
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

**Comment by dsolanki-initos** [comment]
@Vimal-OSI Can you make pre-commit happy?

**Comment by dsolanki-initos** [comment]
@Vimal-OSI it would be nice if you resolve the precommit issue.

**Review by dsolanki-initos — APPROVED** [review]
Code review and functional test LGTM

**Comment by dsolanki-initos** [comment]
Can we get the reviews here?

**Comment by dsolanki-initos** [comment]
@max3903 and @osi-scampbell it would be nice if you add reviews here.

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Comment by dsolanki-initos** [comment]
@pedrobaeza  Could you merge this?

**Comment by pedrobaeza** [comment]
OK, trusting in the reviewers:

/ocabot merge nobump

/ocabot migration agreement_repair

**Pull request merged**
