### PR TITLE
[14.0][ADD] agreement_legal_contract

### PR DESCRIPTION
**Pull request by newtratip**
This module is connector between `agreement_legal` and `contract`.

cc: @aomorawanc

### CODE REVIEW

**Comment by etobella** [comment]
@newtratip I have been checking your module but I have one question.

You are relating the agreement with contract, but shouldn't be related to contract line?

Let me explain. We usually manage maintenance contracts. Each renewal we will create a new agreement (a renewal), but the contract should be the same with several lines. WDYT?

If you like the idea. We can make a proposal keeping your commits.

**Comment by kittiu** [comment]
@etobella I am interested to hear your use case. Do you mean by, i.e.,

* Agreement with 3 product lines -> create Contract with 3 lines
* then, renew Agreement (with no line, but refer to old Agreement) -> create Contract with 3 lines

OR

* Agreement with 0 product lines (don't care lines) -> create Contract with 3 lines
* then, renew Agreement -> create Contract with 3 lines.

> You are relating the agreement with contract, but shouldn't be related to contract line?

Are you saying, agreement OR agreement.line that related to contract.line ? I also not clear why you think current relation between agreement and contract is not enough for your case.

I am sorry, not sure you still remember the case, it was quite sometime.

**Comment by rousseldenis** [comment]
@etobella Could you answer @kittiu questions ?

**Comment by rousseldenis** [comment]
@kittiu My question: Why depending on agreement_legal and not just on agreement as far as I can see, no code depends on that one?

**Comment by etobella** [comment]
> @etobella I am interested to hear your use case. Do you mean by, i.e.,
> 
> * Agreement with 3 product lines -> create Contract with 3 lines
> * then, renew Agreement (with no line, but refer to old Agreement) -> create Contract with 3 lines

It might be possible to add the renewal on the same contract :thinking: 

> 
> OR
> 
> * Agreement with 0 product lines (don't care lines) -> create Contract with 3 lines
> * then, renew Agreement -> create Contract with 3 lines.
> 
> > You are relating the agreement with contract, but shouldn't be related to contract line?
> 
> Are you saying, agreement OR agreement.line that related to contract.line ? I also not clear why you think current relation between agreement and contract is not enough for your case.

I think it is better to relate agreement line with contract line.

> 
> I am sorry, not sure you still remember the case, it was quite sometime.

**Comment by nimarosa** [comment]
Hello, I want to reopen this discusión since I think a link into agreement and contract are more than necessary. I think the user expect contract and agreements linked.

**Pull request closed without merging**
