### PR TITLE
[14.0][ENH] agreement_legal

### LINKED ISSUE #502: [12.0][BUG] agreement_legal: wrong revision date
When creating a new version for an agreement, the creation date of the "OLD" version is set to today while the date of the "NEW" version is still the date when the 1st version was created.
These two dates should be switched.

### LINKED ISSUE #640: [CE ver 12] - Problem : "Internal Reference Code" is not generated properly when click Template "New Agreement" button
Hello,

I am using
Odoo CE Ver. 12

I have installed :
- agreement ver 12.0.1.2.0
- agreement_legal ver 12.0.2.0.0

Problem :
1. I have created a Agreement Template - Reference "AG001"( Configuration - Templates )
2. From the created Template, I click "New Agreement" button
3. A new agreement is generated, however the "Reference" is not correct and the Title is "NEW" instead of referring back to Template Title
4. A new agreement reference is "AG001 (copy)". I was hoping the new agreement reference is "AG002"
5. Is this intentional or a bug?

Thank you and hope to get your feedback.

PS: I attach Documentation Picture as follows :

### PR DESCRIPTION
**Pull request by newtratip**
**Edited**

- Add terminated stage
- Remove duplicate `ir.module.category` (Agreement)
- Remove model not used
  - `agreement.renewaltype` 
  - `agreement.increasetype`
- Remove file not used 
  - `agreement_status.py`
  - `product_template.py`
- Remove field not used
  - Description field in `agreement.stage`
  - Term field in `agreement`
  -  Currency field in `agreement`
  - Product_ids field in `agreement`
- Add active field on submenu of configuration menu
  - Stages
  - Sub-Types
- Add search view
  - Stages
  - Sub-Types
- Add context `{'default_is_template': False}` on the agreement and `{'default_is_template': True}` on the template
- Invisible is_template field
- Add web_ribbon on template
- Hide agreement field on recital, section, clause, appendix on the agreement
- Remove domain widget, it's not used.
- Stage in agreement form view can not click, I add clickable=1 to it
- Add default agreement's stage is New
- Reset agreement revision to 0 since it's a new agreement version
- Fixed https://github.com/OCA/contract/issues/640
- Fixed missing save button https://github.com/OCA/contract/issues/500
- Fixed https://github.com/OCA/contract/issues/502 (switched created by and created date)
- Agreement user role can create agreement from template
Selection_363
- Agreement can not edit if setting readonly = True in stage
Selection_359

I have fix following above, Could you review this ? 
@patrickrwilson @ygol @kittiu

### CODE REVIEW

**Review by ygol — COMMENTED** [review]
Hi @newtratip .  
LGTM

Two remarks:

- There are warning in the log following the removal of the different fields:

> WARNING stag odoo.addons.base.models.ir_model: Deleting field agreement.increasetype.name (hint: fields should be explicitly removed by an upgrade script) 

- Maybe the wizard will be better as a button added to the kanban & list header view?

Thanks.

@max3903 and others:
I do not use the following removed fields & models. So I don't mindit. 
Are you ok with that?

- renewaltype
- increatype
- agreement_status.py
- product_template.py
- Description field in agreement.stage
- Term field in agreement
- Currency field in agreement
- Product_ids field in agreement

**Comment by newtratip** [comment]
Hello @ygol,

- There are warning in the log following the removal of the different fields
> I didn't see the warning, please suggest me to find this.

- Maybe the wizard will be better as a button added to the kanban & list header view?
> What is mean `added to the kanban & list header view` ?

**Comment by ygol** [comment]
> Hello @ygol,
> 
> * There are warning in the log following the removal of the different fields
> 
> > I didn't see the warning, please suggest me to find this.

this is the log when upgrading the module in an existing instance.
image




> * Maybe the wizard will be better as a button added to the kanban & list header view?
> 
> > What is mean `added to the kanban & list header view` ?

image

**Comment by newtratip** [comment]
Hello @ygol,

1. I think warning in the log is not a problem when first install or upgrade on the existing instance times 2, 3, 4, .... not display **"WARNING"** anymore.
2. I added `Create From Template` on the kanban & list header view
Selection_362
Peek 2021-07-19 22-24

**Review by ygol — APPROVED** [review]
LGTM

**Review by Saran440 — APPROVED** [review]
LGTM :+1: 

Could you rebase this PR into 1 ?

**Comment by newtratip** [comment]
Rebased.

**Comment by ygol** [comment]
@newtratip I think it is  a mistake to disactivate the option to duplicate an agreement. Without it you would be forced to start a new template from scratch versus taking a copy of an existing one and adapting it.

I also thing that there should be the option to save an agreement as a template

**Comment by newtratip** [comment]
@ygol, Activated the option to duplicate https://github.com/OCA/contract/pull/700/commits/228ae55b3404726fb7bc8eb19ce6c61395250b96, please check this.

**Comment by newtratip** [comment]
Now, the agreement user role can create, edit in Structure (Recitals, Section, Clauses, Appendix) and Products/Services **BUT** can't delete it. IMO, they should delete. I would like to add unlink permission in access right with the user. @ygol What do you think ?
Selection_365

**Comment by ygol** [comment]
> Now, the agreement user role can create, edit in Structure (Recitals, Section, Clauses, Appendix) and Products/Services **BUT** can't delete it. IMO, they should delete. I would like to add unlink permission in access right with the user. @ygol What do you think ?

- I agree that if the user can add to the structure (Recitals, Section, Clauses, Appendix) then he should be able to delete it too.

(one of the todo I have is to create the parts as "templates" themselves and let a user select the parts to be added in an agreement. In that case a user would only be able to add and remove parts from the agreement but not modify them. But this will have to be thouroughly tested first)

**Comment by newtratip** [comment]
Fixed https://github.com/OCA/contract/pull/700/commits/eee8e31744d283dbbc890021e03b7a87410c39d6, user role should be able to delete in recital, section, clause, appendix, product line.

**Comment by ygol** [comment]
Who should merge it? @dreispt ?

**Pull request merged**
