### PR TITLE
[FIX] contract: remove groupby if it is in context

### PR DESCRIPTION
**Pull request by len-foss**
Co-authored by @Lopsanz

rebase/cleanup of https://github.com/OCA/contract/pull/569

### CODE REVIEW

**Comment by pedrobaeza** [comment]
It seems there's an error in tests due to this.

**Comment by len-foss** [comment]
Hello @pedrobaeza 
Sorry, of course I always mess up dict comprehension the first time.

**Comment by pedrobaeza** [comment]
Let's merge it finally!

/ocabot merge patch

**Comment by pedrobaeza** [comment]
Needed in v13?

**Comment by len-foss** [comment]
I believe so, I don't think there has been any change regarding context-passing in view/actions in the framework. I'll forward-port in a few.

**Pull request merged**
