### PR TITLE
[IMP] agreement_legal: Multi-level field selector

### PR DESCRIPTION
**Pull request by smangukiya**
w.r.t: https://github.com/OCA/contract/issues/335

Module needs upgrade:
> agreement_legal

Here is the example of agreement.recital:

Image 1: (It will provide domain widget popup to generate dynamic field string)
dynamic_content_popup

Image 2: It will show dynamically generated string:
dynamic_content

@max3903

### CODE REVIEW

**Comment by max3903** [comment]
@smangukiya I will take care of the other fields. Thank you!

**Review by max3903 — APPROVED** [review]

**Review by ygol — COMMENTED** [review]
It seems to work fine in the runbot for the recitals model but all other such fields are still using the previous "field_id". maybe we need a fresh runbot instance to be rebuild?!

**Review by ygol — APPROVED** [review]
LGTM

**Review by patrickrwilson — APPROVED** [review]
I tested this and it does seem to work as intended.

**Comment by nikul-serpentcs** [comment]
`Merge branch '12.0' into 12.0-imp-16335-dynamic-content`

@max3903 Regarding Commit message
FYI You are directly used `git pull upstream`
here Best way to using rebase: `git rebase upstream`, So this msg will not come and you get latest commit's 

Thank you!!

**Pull request merged**
