### PR TITLE
[13.0][ADD] copier

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
GH actions are being executed even in the PR. That didn't work before. I think what doesn't work is to merge with ocabot.

**Comment by rousseldenis** [comment]
> I think what doesn't work is to merge with ocabot.

Yes, wait a bit. I'll merge when it's ok

**Comment by rousseldenis** [comment]
@pedrobaeza I have promoted two modules but that one depends on a Beta.

In order to merge this we need to set it back to Beta. Are you ok with that ?

image

**Comment by pedrobaeza** [comment]
OK. We'll promote later the main one to `stable`, being there for several versions and with tests.

**Pull request merged**
