### PR TITLE
[12.0][MIG] - Migration module contract_sale_invoicing to 12.0 

### PR DESCRIPTION
**Pull request by sbejaoui**
Depends on:

- [x] contract - #202

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You can rebase now

**Comment by rafaelbn** [comment]
Hi @sbejaoui could you please review travis :red_circle: ? Thank you!

**Comment by sbejaoui** [comment]
Hi @rafaelbn ,

Thank you for the reminder, it's green now.

**Review by tbaden — COMMENTED** [review]
code review: lgtm

please squash your commits. I'll approve then

**Review by rafaelbn — APPROVED** [review]
Tested functionally in runbot :+1:

**Comment by rafaelbn** [comment]
@tbaden please could you finish you review? @ThomasBinsfeld can squash the commints :smile: 

Let's finish this one thanks

**Comment by ThomasBinsfeld** [comment]
Commits squashed

**Review by tbaden — APPROVED** [review]

**Comment by nikul-serpentcs** [comment]
@sbejaoui Fix Transifex commit's ` OCA Transbot updated translations from Transifex`

**Pull request merged**
