### PR TITLE
[14.0][MIG] agreement_legal_sale (Version 12.0 to 14.0)

### PR DESCRIPTION
**Pull request by patrickrwilson**
Depends on #669

### CODE REVIEW

**Comment by dsolanki-initos** [comment]
Hi @patrickrwilson 
Can you please fix the failed checks?

**Review by dsolanki-initos — APPROVED** [review]
Code review and Functional test. LGTM

**Comment by dsolanki-initos** [comment]
It would be great if we could merge this?

**Comment by dsolanki-initos** [comment]
It would be great if we could merge this?

**Comment by hpatelserpentcs** [comment]
Test coverage improved

**Comment by patrickrwilson** [comment]
@smangukiya @osi-scampbell can you please review?

**Comment by hkapatel-initos** [comment]
it would be nice if we get reviews here.

**Comment by hkapatel-initos** [comment]
it would be nice if we get reviews here.

**Comment by hkapatel-initos** [comment]
it would be nice if we get reviews here.

**Comment by hkapatel-initos** [comment]
it would be nice if we get reviews here.

**Comment by hkapatel-initos** [comment]
it would be nice if we get reviews here.

**Comment by hkapatel-initos** [comment]
it would be nice if we get reviews here.

**Comment by hkapatel-initos** [comment]
All the cheks are passed it would be nice if anyone can add a review here.

**Comment by dsolanki-initos** [comment]
it would be nice if we get reviews here.

**Comment by dsolanki-initos** [comment]
it would be nice if we get reviews here.

**Comment by dsolanki-initos** [comment]
it would be nice if we get reviews here.

**Review by smangukiya — APPROVED** [review]
LGTM

**Comment by hkapatel-initos** [comment]
@dreispt Can we merge this?

**Comment by dsolanki-initos** [comment]
@dreispt Can you try to merge it again?

**Pull request merged**
