### PR TITLE
[12.0][MIG] contract_variable_qty_timesheet: Migration to 12.0

### PR DESCRIPTION
**Pull request by pedrobaeza**
* Standard procedure
* README by fragments
* Promoted to Production/Stable and declared maintainers
* Code adapted to v12
* Tests added

cc @Tecnativa TT19363

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Unrelated Travis error is tracked in #425

**Review by sbejaoui — APPROVED** [review]
LGTM, Code review

**Review by carlosdauden — APPROVED** [review]
Code review.
Approve if test green.

**Pull request merged**
