### PR TITLE
[13.0][FIX] contract: consistency between contract count and contract action

### PR DESCRIPTION
**Pull request by newtratip**
Move domain in `context` to `action` for filter partner + child partner

domain in context not filter `partner` as picture below
Selection_173
Selection_174

cc: @len-foss

### CODE REVIEW

**Comment by newtratip** [comment]
@OCA/project-service-maintainers, Could you review this ?

**Comment by newtratip** [comment]
@kittiu, @ps-tubtim, @Saran440 Can you help review this ?

**Review by ps-tubtim — APPROVED** [review]
Code LGTM.

**Review by len-foss — APPROVED** [review]
Hello! Sorry it fell under my radar.
It's a bit better to have the explicit filter indeed. The previous PR went very fast because it solved an issue that was apparently annoying to a lot of people, but that meant there wasn't much time to reflect on getting the best solution. Thanks for the heads up!

**Pull request merged**
