### PR TITLE
[13.0] [MIG] contract_layout_category_hide_detail: Migration to v13.0 

### PR DESCRIPTION
**Pull request by victoralmau**
Required https://github.com/OCA/contract/pull/533

@Tecnativa TT26073

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please put the PR title according guidelines.

**Comment by pedrobaeza** [comment]
Please rebase

**Review by sbejaoui — APPROVED** [review]
LGTM, Thank you

**Comment by tonygalmiche** [comment]
On sale.order, I can see the icons on the right : 
image

But not on contract.contract : 
image

**Comment by victoralmau** [comment]
> On sale.order, I can see the icons on the right :
> image
> 
> But not on contract.contract :
> image

Sorry, i don't understand exactly the problem because this addon is related to contracts only.

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
@victoralmau @tonygalmiche was setting a comparison with sales for showing that the module is not working properly:

Selección_007

Please rebase after #571, and check locally if it works.

**Comment by victoralmau** [comment]
@pedrobaeza  Sorry but in contract 13.0 with runbot and inside test contract don't appear (pause and renew icons). 
It´s an error related to `contract_layout_category_hide_detail` or `contract`?

**Comment by victoralmau** [comment]
@tonygalmiche @pedrobaeza  Sorry for confusion about icons, now work fine.

**Comment by tonygalmiche** [comment]
in sale.order, the position of the icons is correct:
image

But not on contract.contract :
image

**Comment by victoralmau** [comment]
> in sale.order, the position of the icons is correct:
> image
> 
> But not on contract.contract :
> image

Sorry, i had checked runbot and IMO it's ok:
sale_order (S00020):
runbot-sale_order
contract (test):
runbot-contract

**Review by pedrobaeza — APPROVED** [review]
Tried on runbot and working, although I have discovered a problem creating invoices for sections, that is on the main module and will fix it later.

Code review as well

**Pull request merged**
