### PR TITLE
[10.0][FIX] Fix Travis

### PR DESCRIPTION
**Pull request by pedrobaeza**
Trying to fix Travis result

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Still the problem... @lasley any clue for fixing tests of your module contact_payment_auto? (Travis issue?)

**Comment by pedrobaeza** [comment]
Still the problem... @lasley any clue for fixing tests of your module contact_payment_auto? (Travis issue?)

**Comment by lasley** [comment]
No idea. I'm removing tests and will submit a patch

**Review by lasley — APPROVED** [review]

**Comment by pedrobaeza** [comment]
OK, although I don't like too much to change test types because it takes more time to be finished, as seen, it's the only solution, so I merge to get a green CI. Please check on time (on the PR) next time before making this bigger.

**Pull request merged**
