### PR TITLE
[IMP] Icon

### PR DESCRIPTION
**Pull request by max3903**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you please provide the SVG source? The icon have very low quality any way (not resolution).

**Comment by max3903** [comment]
@pedrobaeza Let me ask.

**Comment by pedrobaeza** [comment]
That is cheating...

The SVG contains the same low-quality bitmap:

seleccion_038

**Comment by max3903** [comment]
@pedrobaeza I know :) but that's what I have. :(

**Comment by pedrobaeza** [comment]
You can do it from scratch using Inkscape + Font Awesome TTF/OTF. This one is not good enough for being included IMO.

**Pull request closed without merging**
