### PR TITLE
[14.0][MIG] agreement_account (Version 12.0 to 14.0)

### PR DESCRIPTION
**Pull request by patrickrwilson**

### CODE REVIEW

**Comment by patrickrwilson** [comment]
FYI: I will work on tests when I get a chance.

**Comment by hpatelserpentcs** [comment]
@patrickrwilson 
Tests Added

**Comment by patrickrwilson** [comment]
@smangukiya @osi-scampbell can you please review?

**Comment by dsolanki-initos** [comment]
Hi @patrickrwilson 
Can you please adjust the commits as per the guideline?

**Review by dsolanki-initos — APPROVED** [review]
Code review LGTM

**Comment by dsolanki-initos** [comment]
it would be great if someone reviews here.

**Comment by dsolanki-initos** [comment]
it would be great if someone reviews here.

**Review by smangukiya — APPROVED** [review]
LGTM

**Comment by dsolanki-initos** [comment]
@dreispt It would be nice if we could merge it.

**Pull request merged**
