### PR TITLE
16.0 mig contract sale generation

### PR DESCRIPTION
**Pull request by vibhascs**

### CODE REVIEW

**Review by NotJaime13 — COMMENTED** [review]
Funtional review ok!

**Comment by rousseldenis** [comment]
@vibhascs Could you follow migration guide, especially Full process part as some changes should appear in pre-commit stuff commit ? Thanks

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

**Review by manuelcalerosolis — APPROVED** [review]
Funtional review ok!

**Comment by rousseldenis** [comment]
@vibhascs Do you mind if we switch to #955 ?

**Pull request closed without merging**
