### PR TITLE
[14.0][IMP] subscription_oca: enable markers to print invoice names

### PR DESCRIPTION
**Pull request by PicchiSeba**
(like in _contract_)

### CODE REVIEW

**Comment by PicchiSeba** [comment]
I just updated the tests. I see that there is one failing on the current 14.0 version (`test_x_subscription_oca_pricelist_related_2`)

This failure can be seen in another PR as well: https://github.com/OCA/contract/pull/1028

**Comment by PicchiSeba** [comment]
Rebased on top of #1034

**Review by HekkiMelody — APPROVED** [review]
Code review, LGTM.

It may be worthwhile to add a test that the markers are being replaced properly.

**Review by francesco-ooops — APPROVED** [review]
Functional ok!

**Review by renda-dev — APPROVED** [review]
/ocabot merge minor

**Pull request merged**
