### PR TITLE
[14.0][FIX] subscription_oca: product-subscription_template company issues

### PR DESCRIPTION
**Pull request by HekkiMelody**
Make company required on subscription_template.

Make subcription_template_id a company-dependent field on product_template.

On SO, set a team whose company is consistent with the SO's company.

TODO:
  - [x] must verify migration of existing data

Migration of existing data is necessarily imperfect, because previous data may be inconsistent in the first place.

### CODE REVIEW

**Review by PicchiSeba — APPROVED** [review]
Code Review: LGTM

**Review by PicchiSeba — APPROVED** [review]
Code Review: I haven't personally tried it but just by looking, it seems good.

**Review by francesco-ooops — APPROVED** [review]
Funzionale ok

**Pull request merged**
