### PR TITLE
[14.0][FIX] contract/contract_sale_generation: Compute correctly the recurring next date after stop()

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I think this is fixed in a simpler way in https://github.com/OCA/contract/pull/853

**Comment by rousseldenis** [comment]
> I think this is fixed in a simpler way in #853

That is certainly one piece.

But this is a particular case.

**Comment by pedrobaeza** [comment]
I think reverting part of the 14.0 changes and applying the fix will fix it. Please check #854 for that .

**Review by CRogos — APPROVED** [review]
Code and functional test LGTM.

**Comment by rousseldenis** [comment]
@CRogos @pedrobaeza this one runs in production for weeks. So, IMHO we can reasonably merge it

**Comment by pedrobaeza** [comment]
#854 is more suitable and align the versions. If anything non covered, please indicate and I'll fix it.

**Comment by CRogos** [comment]
@rousseldenis this PR is a huge improvement in the behavior regarding the next invoice date. Thanks a lot!

I just found one little issue when creating a contract with "Recurrence at line level?" in the past (ending before today). Than the "Generate Recurring Invoices from Contract" Server Action is not creating a invoice. Using the "Create Invoice" button is working.
image

**Comment by CRogos** [comment]
@victoralmau could you review this commit?

**Comment by rafaelbn** [comment]
Please @rousseldenis , could you rebase?

**Comment by rafaelbn** [comment]
Why not merge https://github.com/OCA/contract/pull/854 that was made 4th July and merged in 13 and after merge, rebase here and make whatever should be done?

**Comment by rafaelbn** [comment]
Hello @rousseldenis , I would like to review but I can, Could you rebase please?

I have no answer in https://github.com/OCA/contract/pull/854

**Comment by rafaelbn** [comment]
Let see if runboat works

**Review by rafaelbn — APPROVED** [review]
👍 

We should fix and fordward port

**Review by flotho — APPROVED** [review]
thanks for this fix

**Comment by pedrobaeza** [comment]
OK, I give up and let's merge this one instead mine, and see what happens, as I haven't got time to explore other solutions:

/ocabot merge patch

Please fw-port it to upper versions for having homogeneity

**Pull request merged**
