### PR TITLE
[11.0] [MIG] contract

### PR DESCRIPTION
**Pull request by feketemihai**
Migrate contract module to v11. 

On format-patch i had a lot of issues i think from the rename of the modules, and i don't know how to fix all the patches...i just skipped them...

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please follow migration guide: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0 for respecting commit history instead of that strange `[PATCH ...]` commit message. It would be interesting also to include #107 in this migration.

**Comment by feketemihai** [comment]
@pedrobaeza I used the same procedure from the wiki, but i think the rename of the modules plus extra requirements of the code since it was extracted from Odoo base gave me some errors in patching the commits, i will add tomorow the extra work from #107...even that is not merged...

**Comment by pedrobaeza** [comment]
You have missed a lot of authors with your technique, so please try again. Merge operations indeed can break the process, but you have to solve the conflicts instead applying a weird kind of cherry-picking / renaming.

**Comment by feketemihai** [comment]
I used this command and a lot of errors over fetching commits raised

git format-patch --keep-subject --stdout origin/11.0..origin/10.0 -- contract | git am -3 --keep

**Comment by pedrobaeza** [comment]
What kind of errors?

**Pull request closed without merging**
