### PR TITLE
[17.0][MIG] contract: Migration to 17.0

### PR DESCRIPTION
**Pull request by peluko00**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please check CI and cherry-pick here #1050

**Comment by jaydeep32** [comment]
I have migrated test cases and a few things in the mail XML template. So if I want to push that, could you please tell me how I can do that?

**Comment by pedrobaeza** [comment]
Please fix the CI and include #1059

**Comment by pedrobaeza** [comment]
Please cherry-pick #1054 as well

**Comment by CRogos** [comment]
please close, supersede by #1067

**Pull request closed without merging**
