### PR TITLE
[13.0][FIX]: contract: Migration script check if column old_invoice_line_id exists

### PR DESCRIPTION
**Pull request by EmilioPascual**
@Shide @edlopen please review.

@moduon MT-6161

### CODE REVIEW

**Review by Shide — APPROVED** [review]

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Starting with, please put the contrary condition and return early for minimizing the diff.

This seems to avoid crashes when coming from an enterprise migration, so masking all scripts is not the correct formula and you will have more troubles as intermediate DB schemas are not applied. 

Please don't pollute OCA with these hacks.

**Comment by rafaelbn** [comment]
Dear @pedrobaeza ,

I appreciate your input on this PR. However, I would like to kindly remind you that the OCA's Code of Conduct encourages us to contribute positively to the community. Your response seems to be more focused on assumptions rather than on constructive feedback. The purpose of this PR is to correct an issue without causing any breakage, and it would be more productive to focus on whether it technically resolves the problem without introducing new issues.

Thank you for your understanding and collaboration.

Best regards,  
@rafaelbn 

Ping @OCA/project-service-maintainers

**Comment by pedrobaeza** [comment]
Is my assumption incorrect?

**Comment by rafaelbn** [comment]
Your assumption is an assumption. Is the PR incorrect? Breaks something?

**Pull request closed without merging**
