### PR TITLE
[16.0] [MIG] contract_payment_mode

### PR DESCRIPTION
**Pull request by angelmoya**

### CODE REVIEW

**Review by astirpe — APPROVED** [review]
LGTM!


Shouldn't fd9c996493ab5a4f95d95af03351009000dd3a9f be also backported to previous versions?

**Comment by victor-champonnois** [comment]
@angelmoya I would like to test but the runboat is pending (also other tests in the CI are not present). Do you know why ? Could you fix this ? Thanks !

**Comment by rousseldenis** [comment]
@angelmoya Could you rebase ?

**Comment by 10537** [comment]
Hi @angelmoya,

Please, Could you rebase this branch?

**Comment by PauMAVA** [comment]
Hi, when will this be merged into 16.0? `contract_mandate` #962 depends on this.

**Comment by carolinafernandez-tecnativa** [comment]
@angelmoya could you please rebase ?

**Comment by pedrobaeza** [comment]
Supersede by #996

**Pull request closed without merging**
