### PR TITLE
[14.0] [MIG] contract_invoice_start_end_dates

### PR DESCRIPTION
**Pull request by chafique-delli**

### CODE REVIEW

**Comment by chafique-delli** [comment]
@florian-dacosta

**Review by angelmoya — APPROVED** [review]

**Comment by marylla** [comment]
@chafique-delli Hi there, I'd like to test it in runboat but it doesn't work. Do you need to rebase maybe?

**Review by florian-dacosta — APPROVED** [review]

**Comment by marylla** [comment]
@chafique-delli Can you please continue your work on this PR? :)

**Review by mourad-ehm — APPROVED** [review]

**Comment by etobella** [comment]
Can you rebase and remove the merge commit?

**Comment by florian-dacosta** [comment]
@marylla @leemannd @etobella Seems it is all good now

**Review by etobella — APPROVED** [review]
LGTM /ocabot merge nobump

**Pull request merged**
