### PR TITLE
[15.0 ][MIG] contract_sale

### PR DESCRIPTION
**Pull request by JoanMForgeFlow**
Migration of the module contract_sale at version 15.0.
Waiting to being stable: https://github.com/OCA/contract/pull/774
@forgeflow

### CODE REVIEW

**Comment by JoanMForgeFlow** [comment]
Now its green

**Review by AaronHForgeFlow — APPROVED** [review]
It works

**Review by mariadforgeflow — APPROVED** [review]
LGTM!!

**Pull request merged**
