### PR TITLE
[14.0][MIG] Migarted contract_payment_mode module.

### PR DESCRIPTION
**Pull request by AmmarOfficewalaSerpentCS**

### CODE REVIEW

**Comment by AmmarOfficewalaSerpentCS** [comment]
@dreispt , @max3903 , @murtuzasaleh , @smangukiya 

Can you please review this PR?

**Comment by bosd** [comment]
Hi @AmmarOfficewalaSerpentCS 
Can you follow the OCA procedure for porting an module?
There should be a seperate commit for black,prettier etcetera.

After the black and prettier commit there should be an migration commit.
The  Readme.rst files don't need manuale change as they are automatically updated by the bot.

**Review by dsolanki-initos — APPROVED** [review]
Functional tests and code review.

**Pull request merged**
