### PR TITLE
12.0 mig contract payment auto fix

### PR DESCRIPTION
**Pull request by fcayre**
This PR supersedes #448 as the original author does not seam to be active on it anymore.

### CODE REVIEW

**Comment by rousseldenis** [comment]
@fcayre Have you signed CLA ?

**Comment by rousseldenis** [comment]
> @fcayre Have you signed CLA ?

Ok, former github account

**Review by rousseldenis — APPROVED** [review]
@fcayre Thanks for this. Looks great.

Could you squash your commits?

**Comment by fcayre** [comment]
@rousseldenis done, sorry for the delay.

**Comment by rousseldenis** [comment]
@fcayre Ooops, I think you were a little bit too restrictive. You should keep history from former branches.

**Pull request closed without merging**
