### PR TITLE
Oca port pr 792 from 14.0 to 15.0

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@pedrobaeza

**Comment by rousseldenis** [comment]
Thanks to 
image

:sweat_smile:

**Review by pedrobaeza — APPROVED** [review]
I don't think this deserves 4 commits to be added on the commit history, some of them undoing part of what was done on the previous ones, but it seems I'm the only one with this feeling.

**Comment by rousseldenis** [comment]
> I don't think this deserves 4 commits to be added on the commit history, some of them undoing part of what was done on the previous ones, but it seems I'm the only one with this feeling.

Each one has its own signification and has sense separately. I didn't do commits with just 'fix' comment. Coding is writing a story. :wink:

**Comment by pedrobaeza** [comment]
For me (and your future you), that history is not adding too much value IMO. The important thing is the final decisions, and put in code the relevant whys, and in commit message, the expanded history (if needed). Both principles has saved me from screwing up things when coming back to the code after some time, not such commit history. But that's my opinion, of course.

**Review by flotho — APPROVED** [review]
easy port.
LGTM
Thanks @rousseldenis

**Pull request merged**
