### PR TITLE
[12.0][IMP] New icon for agreement modules (svg file in agreement_legal)

### PR DESCRIPTION
**Pull request by marcelsavegnago**
I made a new icon for the agreement modules since I didn't get the SVG file for the current icon. In the main menu, the current icon is smaller than the other icons when the web_responsive module is activated. In addition, the proposed new icon already makes it close to the standard of current Odoo icons.

image

https://github.com/OCA/contract/issues/463

### CODE REVIEW

**Review by max3903 — APPROVED** [review]

**Comment by pedrobaeza** [comment]
I'm missing the XML for loading that icon in the main menu.

It would be also interesting to add little variations of the icon according the module for differentiating them on the module list.

**Review by patrickrwilson — APPROVED** [review]
Looks great! LGTM

**Comment by max3903** [comment]
@pedrobaeza It's already there:
https://github.com/OCA/contract/blob/12.0/agreement_legal/views/menu.xml#L11

For the variations, please open an issue.

**Pull request merged**
