### PR TITLE
[12.0][FIX] contract: consistency between contract count and contract action

### PR DESCRIPTION
**Pull request by newtratip**
Move domain in `context` to `action` for filter partner + child partner

domain in context not filter `partner` as picture below
Selection_173
Selection_174

cc: @len-foss

### CODE REVIEW

**Comment by newtratip** [comment]
@OCA/project-service-maintainers, Could you review this ?

**Comment by newtratip** [comment]
@dreispt, same https://github.com/OCA/contract/pull/641, please merge this too.

**Comment by newtratip** [comment]
@Saran440 @ps-tubtim

**Review by marcelsavegnago — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]

**Pull request merged**
