### PR TITLE
12.0 mig agreement base

### PR DESCRIPTION
**Pull request by ygol**
As per #189 and https://github.com/OCA/contract/pull/220#issuecomment-453423098

Would that work for our new "base" model?

- I have generated a new pot file.
- I added myself as a contributor in the __manifest__. Is this correct?

### CODE REVIEW

**Comment by ygol** [comment]
I haven't added groups, permissions as they will be different when used by @alexis-via (part of account) than by @max3903 (specific module permissions). 

I did add a top menu "agreement" though.

**Comment by murtuzasaleh** [comment]
@ygol will you finish this PR?
@max3903 @rafaelbn @pedrobaeza

**Comment by ygol** [comment]
> @ygol will you finish this PR?
> @max3903 @rafaelbn @pedrobaeza
@murtuzasaleh 
I don't know how to resolve the conflict as those are files not in this PR. Beside that, I believe it is ready to be reviewed and merged.

**Comment by max3903** [comment]
Something went wrong when repeating the history from v10. The `contract` stuff should not be here.

@murtuzasaleh Can you help here?

Ref:
Replace 11.0 with 10.0 in this procedure: 
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0#howto

**Comment by murtuzasaleh** [comment]
@ygol Can you please add me as a collaborator in your branch.
[Ref.](https://help.github.com/en/articles/adding-outside-collaborators-to-repositories-in-your-organization)

Why you have created a new branch [#287](https://github.com/OCA/contract/pull/287)?

@max3903

**Comment by ygol** [comment]
> @ygol Can you please add me as a collaborator in your branch.
> [Ref.](https://help.github.com/en/articles/adding-outside-collaborators-to-repositories-in-your-organization)
> 
> Why you have created a new branch [#287](https://github.com/OCA/contract/pull/287)?
> 
> @max3903

@murtuzasaleh I have created #287 because:
- I made some error in #259 
- the module name should be agreement and not agreement_base
- only one squashed commit (cleaner).
Would you please review #287 and get it approved & merged? I will then close #259

**Pull request closed without merging**
