### PR TITLE
[16.0][MIG] contract_payment_mode: Migration to version 16.0

### PR DESCRIPTION
**Pull request by carolinafernandez-tecnativa**
- Standard migration to v16
- Change Setup to SetupClass in tests

@Tecnativa

TT45225

@pedrobaeza @chienandalu 

P.D: Close this PR: https://github.com/OCA/contract/pull/947

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by fcvalgar** [comment]
Good morning @carolinafernandez-tecnativa @pedrobaeza ,

With this PR the Create Invoice button disappears.

image

image

**Comment by carolinafernandez-tecnativa** [comment]
> Good morning @carolinafernandez-tecnativa @pedrobaeza ,
> 
> With this PR the Create Invoice button disappears.
> 
> image
> 
> image

Good morning,

In order to be able to see "Create invoice" button, you should be in developer mode.

Example with developer mode:
image


Example without developer mode:

image


This behavior is standard for the contract module. You can check it here: https://github.com/OCA/contract/blob/16.0/contract/views/contract.xml

**Comment by fcvalgar** [comment]
Thanks for the explanation @carolinafernandez-tecnativa

**Review by fcvalgar — APPROVED** [review]
LGTM, 

Thank you @carolinafernandez-tecnativa 

image

image


image

**Pull request merged**
