### PR TITLE
[15.0] [MIG] agreement module

### PR DESCRIPTION
**Pull request by MosabWadea**
This is my first contribution and I am still learning
Please excuse my mistakes and guide me

Thanks

### CODE REVIEW

**Comment by MosabWadea** [comment]
Hello @pedrobaeza 
I hope this pull request is ok now?

**Comment by pedrobaeza** [comment]
I'm missing the migration commit

**Comment by MosabWadea** [comment]
it is that there was nothing to migrate, I updated the version number after running the pre-commit and did the change in the same commit
other than that the module didn't need any change, should I redo the commit?

**Comment by MosabWadea** [comment]
@pedrobaeza I fixed the commit tree
hope this will do..

Thanks

**Comment by pedrobaeza** [comment]
👍

**Comment by MosabWadea** [comment]
hello @pedrobaeza I have upgraded the other agreement modules as well but I can't pull request as this one is not merged yet and this module is in the dependency of the others, so I have two questions:
1- can I have a pull request for all modules together?
2- do I have to do anything for this pull request or just in the review process?

Thanks

**Comment by pedrobaeza** [comment]
When this module is merged, you rebase the rest of the pull requests. For getting this module reviewed, review other pull requests in this repo or similar ones and ask in exchange that they review yours.

**Comment by MosabWadea** [comment]
can you please help me with a link to explain what to do in a review process
sorry if I am asking a lot and thanks for your support

**Comment by pedrobaeza** [comment]
https://odoo-community.org/page/review
https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#review

**Comment by MosabWadea** [comment]
also can you please let me know what you mean by "rebase the rest of the pull requests"?

**Comment by MosabWadea** [comment]
@kelvzxu can you please review this pr?

**Review by kelvzxu — APPROVED** [review]
Code review  :+1:

**Comment by MosabWadea** [comment]
> Code review +1

Thanks :)

**Comment by MosabWadea** [comment]
@JoanMForgeFlow can you please review this PR

Thanks

**Review by jeezany — APPROVED** [review]
Approved

**Comment by MosabWadea** [comment]
hello @pedrobaeza I have two reviews now, will this pr be merged or I need to do something first?

Thanks

**Comment by pedrobaeza** [comment]
One of the reviews must come at least from someone trustable like a PSC or a maintainer

**Comment by MosabWadea** [comment]
Thanks @pedrobaeza but I am trying to search for a community member to approve however, I am not sure how to find one. Can you please approve this PR 
Thanks

**Comment by rousseldenis** [comment]
@MosabWadea Before merging this, I'm wondering if an agreement repository would not be nice after a discussion I recently had.

@OCA/core-maintainers What do you think of ?

**Comment by rousseldenis** [comment]
@OCA/project-service-maintainers

**Comment by pedrobaeza** [comment]
OK for me to split.

**Comment by simahawk** [comment]
shall I create an OCA/agreement repo then? Same PSC?

**Comment by rousseldenis** [comment]
> shall I create an OCA/agreement repo then? Same PSC?

@simahawk  Seems legit. Thanks !

**Comment by simahawk** [comment]
https://github.com/OCA/agreement

**Comment by rousseldenis** [comment]
@MosabWadea Could you switch to that repo ? It's ready

**Comment by MosabWadea** [comment]
@rousseldenis Sure will do

**Comment by rousseldenis** [comment]
> @rousseldenis Sure will do

@MosabWadea When do you plan to do the first PR on agreement repo ?

**Comment by MosabWadea** [comment]
@rousseldenis I am planning to work on it tomorrow or maybe Sunday.

**Comment by MosabWadea** [comment]
@rousseldenis I was wondering how to move the agreement module in git  from contract repo to agreement, while following the oca guide lines.
can you please give me git commands to follow

Thanks

**Comment by marylla** [comment]
@rousseldenis @MosabWadea I am not sure if there is a better way but... you could just create a new PR in the new agreement repo. I'd like to review then if needed. :)

**Comment by rousseldenis** [comment]
> @rousseldenis I was wondering how to move the agreement module in git from contract repo to agreement, while following the oca guide lines. can you please give me git commands to follow
> 
> Thanks

@MosabWadea 

You can do it quite easily.

On your local agreement repo:

`git remote add contract git@github.com/MosabWadea/contract.git`

`git fetch contract`

`git checkout -b <your branch name> agreement/15.0`

`git format-patch --keep-subject --stdout agreement/15.0..contract/15.0-mig-agreement -- agreement | git am -3 --keep`

Then, make a PR like normally

**Comment by rousseldenis** [comment]
@MosabWadea Can you review that one instead as  @etobella has done the job ? https://github.com/OCA/pull/2

**Comment by rvalyi** [comment]
the proper link is actually https://github.com/OCA/agreement/pull/2

**Pull request closed without merging**
