### PR TITLE
[16.0][MIG] contract_mandate: Migration to 16.0

### PR DESCRIPTION
**Pull request by adriapalleja**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@adriapalleja Thanks for this.

Could you follow migration guide : https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0#technical-method-to-migrate-a-module-from-150-to-160-branch ?

And could you fix tests ?

**Review by Sou15 — APPROVED** [review]
Looks good to me, I tried it locally. The module  works, tets work (4/4).

**Review by danypr92 — APPROVED** [review]

**Comment by adriapalleja** [comment]
@rousseldenis Hi! I think this PR is ready to be merged. Could you please merge it please? Thanks!

**Comment by rousseldenis** [comment]
@adriapalleja Could you rearrange your commits and your commit messages ?

image


At least, you should have just after pre-commit one, the migration one `[MIG][16.0] contract_mandate`.

Then, if you have improvements, they should appear clearly with commits like `[IMP] contract_mandate: <the improvement>`.

Thanks

**Comment by adriapalleja** [comment]
Hi @rousseldenis. I fixed the commits following the standards you suggested, thanks! 

There is a check failing in CI, but reviewing inside codecov I would say this is properly working and passing tests. Do you think this is ready now?

**Review by rousseldenis — APPROVED** [review]
Code review

**Pull request merged**
