### PR TITLE
[IMP][14.0] refactor code of product_contract module (make easy inher…

### PR DESCRIPTION
**Pull request by mourad-ehm**
refactor code of product_contract module (make easy inherit in other modules).
Improvement further to discussion in this PR : https://github.com/OCA/contract/pull/933

### CODE REVIEW

**Comment by mourad-ehm** [comment]
HI @rousseldenis,  @francesco-ooops , @hparfr this is the imp version of https://github.com/OCA/contract/pull/933 , could you approve?
Thanks

**Comment by francesco-ooops** [comment]
@ilyasProgrammer could you take a look?

**Review by damdam-s — APPROVED** [review]

**Review by hparfr — APPROVED** [review]
thanks

**Review by elvise — APPROVED** [review]

**Comment by francesco-ooops** [comment]
@OCA/project-service-maintainers could this be merged? thanks!

**Pull request merged**
