### PR TITLE
[15.0][MIG] contract_sale_invoicing: Migration to version 15.0

### PR DESCRIPTION
**Pull request by carolinafernandez-tecnativa**
- Standard migration from v12 to v15.

@Tecnativa

TT45293

@pedrobaeza

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
/ocabot migration contract_sale_invoicing

**Comment by carolinafernandez-tecnativa** [comment]
ping @carlosdauden @pedrobaeza

**Comment by carolinafernandez-tecnativa** [comment]
ping @pedrobaeza @carlosdauden

**Review by victoralmau — APPROVED** [review]

**Pull request merged**
