### PR TITLE
[ADD][12.0] agreement_serviceprofile

### PR DESCRIPTION
**Pull request by murtuzasaleh**
WIP

### CODE REVIEW

**Comment by max3903** [comment]
@murtuzasaleh `agreement_legal` has been merged. Please rebase.

**Comment by murtuzasaleh** [comment]
@max3903 Can you please review this PR.

**Review by max3903 — APPROVED** [review]
LGTM

**Comment by murtuzasaleh** [comment]
@osi-scampbell Can you please review this PR.

**Review by osi-scampbell — APPROVED** [review]

**Pull request merged**
