### PR TITLE
[13.0][FIX] contract: invoices from section contract lines

### PR DESCRIPTION
**Pull request by rousseldenis**
It was impossible to generate invoices from section contract lines.

image

### CODE REVIEW

**Comment by rousseldenis** [comment]
@pedrobaeza

**Comment by pedrobaeza** [comment]
Can you please check pre-commit? Not sure why the account is needed to be populated this way though.

**Comment by rousseldenis** [comment]
> Can you please check pre-commit? Not sure why the account is needed to be populated this way though.

Account is populated through Form() even if section or note. That triggers Odoo constraint in that case. That's because the behaviour is not fully aligned on sale behaviour for example.

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Let's fast-track it for solving the problem:

/ocabot merge patch

**Pull request merged**
