### PR TITLE
[16.0] [MIG] contract_update_last_date_invoiced

### PR DESCRIPTION
**Pull request by edlopen**
Standard migration to v16.

@moduon MT-2061

[Video goes here. WIP.](https://www.loom.com/share/49ea15279efe453eb7d5873e0b655963?sid=7e278d30-7f2a-41e4-980f-f006ba17c128)

@Shide @yajo @rafaelbn please review this when you can. Thank you!

### CODE REVIEW

**Review by yajo — APPROVED** [review]
Code review only.

**Review by Shide — APPROVED** [review]
Code LGTM

**Review by fcvalgar — APPROVED** [review]
Functional review,
LGTM thank you @edlopen 

https://www.loom.com/share/1dd973991786440f80d15ccaa567003b?sid=356c3b0a-02f4-4e48-80fd-1fd753c97c3b

**Review by rafaelbn — APPROVED** [review]
/ocabot migration contract_update_last_date_invoiced


/ocabot merge patch

**Pull request merged**
